### ISSUE TITLE
Dots not aligned when they wrap across multiple rows

### ISSUE THREAD

**Issue by dxcore35** [liamcain/obsidian-calendar-plugin#10]
![Screenshot 2020-10-30 at 14 19 08](https://user-images.githubusercontent.com/7279156/97673913-f618ed00-1aba-11eb-9055-db21fbfe40d8.jpg)

When making the side bar smaller the dots are not aligned to left, and they looks completely chaotic.

**Comment by liamcain** [comment]
This is fixed in the latest release (v1.1.0)

**Comment by dxcore35** [comment]
Still looks broken to me, even in new version.

![Screenshot 2020-10-31 at 14 21 16](https://user-images.githubusercontent.com/7279156/97774215-650e4880-1b84-11eb-91c1-908dfa2e56c2.jpg)

**Comment by liamcain** [comment]
Oh, I thought you meant that the dots weren't round in the original screenshot. Will reopen.

**Comment by liamcain** [comment]
Updated in v1.2.0 so that second row of dots aligns. Be sure to update and restart Obsidian to see the new behavior.
