### ISSUE TITLE
Feature Request:  Set Start Day of Week

### ISSUE THREAD

**Issue by icywolfy** [liamcain/obsidian-calendar-plugin#101]
The default day of week start day is Saturday in many countries.
This plugin does not allow setting the week start to either Friday or Saturday.

Ref: https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/weekData.json#L62
Primarily Calendar week-start day is based on Country, and is language independent.
German-US, Spanish-US, English-US - all start on Sunday
German-DE, Spanish-DE, English-DE - all start on Monday
English-AE, Arabic-AE -- start on Saturday.
English-MV, dv-MV  -- start on Friday.

Arabic should default to "saturday";  or "sunday" in some regions.
Spanish is monday or sunday, depending on country
English is Sunday or monday, and sometimes sat or friday, depending on country of use.

https://help.salesforce.com/articleView?id=000338932&type=1&mode=1 

Moment for AR: correctly shows start day as Saturday: https://github.com/moment/moment/blob/develop/locale/ar.js#L193
This plugin uses Sunday.

**Comment by liamcain** [comment]
This should now be possible in v1.4.13

**Comment by pedy** [comment]
Thanks for everything and especially this feature. But it's inconsistent with #48 . For example, if starting day of week is Saturday, weekend would be Thursday and Friday (Though I'm not sure if every country or company has two days off at the weekend; maybe some have one.)
