### ISSUE TITLE
"Words per dot" word counting is inaccurate

### ISSUE THREAD

**Issue by dsteinbock** [liamcain/obsidian-calendar-plugin#103]
I wrote a note that has 768 words in English (according to the Word Count core plugin). My "words per dot" setting is 250. But only 2 dots are displayed. 

To test it, I added words to the note and the 3rd dot only appeared at 779 words. The word count algorithm must be inaccurate (or uses a _very_ different definition of word count than both the Word Count core plugin and the Better Word Count community plugin). I'd suggest the core Word Count plugin should be used for reference.

**Comment by liamcain** [comment]
Hi, @dsteinbock thanks for the report! 

I can reproduce the issue. The calendar's definition of what a word is is a little too lax. It considers symbols and numerics to be words. So `I caught 2 fish` would be 4 words; whereas the wordcount in the status bar shows that as 3.

I agree that consistency is important here.

**Comment by liamcain** [comment]
Small update on this: Obsidian devs are going to update their definition of what a word is. Once the next version of Obsidian is published, the wordcount will be in sync.

**Comment by liamcain** [comment]
The word count is now in sync with Obsidian v0.10.8, which should be available to the public sometime this week.
