### ISSUE TITLE
(Bug) Loading a workspace will always load calendar pane

### ISSUE THREAD

**Issue by jokysatria** [liamcain/obsidian-calendar-plugin#105]
Step to reproduce
1. Close calendar pane
2. Save current workspace
3. Load current saved workspace

Expected result
- Calendar pane isn't loaded/opened, because it closed before.

Actual result
- Calendar pane is loaded/opened

**Comment by liamcain** [comment]
Great catch! This sames to also happen with the Backlinks view, so I'm not sure if there's an easy/immediate solution. Will see if the devs have any suggestions!

**Comment by liamcain** [comment]
This will be fixed in v0.10.8 of Obsidian 😄

**Comment by jokysatria** [comment]
Just confirm, this bug is fixed. 👍
