### ISSUE TITLE
Weekly note always starts on Sunday

### ISSUE THREAD

**Issue by scotnewbury** [liamcain/obsidian-calendar-plugin#107]
**Current behavior:**
The weekly note pulls the correct dates, Monday through Sunday, but places the Sunday daily note link at the top.

(Assume dates are 1-7)
Daily Note Link to Sunday - the seventh
Daily Note Link to Monday - the first
Daily Note Link to Tuesday
Daily Note Link to Wednesday
Daily Note Link to Thursday
Daily Note Link to Friday
Daily Note Link to Saturday

**Expected behavior:**
When setting the 'start week on' option to Monday the weekly note should run Monday-Sunday.

(Assume dates are 1-7)
Daily Note Link to Monday - the first
Daily Note Link to Tuesday
Daily Note Link to Wednesday
Daily Note Link to Thursday
Daily Note Link to Friday
Daily Note Link to Saturday
Daily Note Link to Sunday - the seventh

Currently  running Obsidian v0.10.7 on Manjaro Linux.

**Comment by liamcain** [comment]
Hi @scotnewbury,

If you are using [this snippet](https://github.com/liamcain/obsidian-calendar-plugin#embed-your-entire-week-in-a-weekly-note) in your weekly note template, you just need to rearrange the days of the week from within the template file.

It sounds like you just want to update your weekly note template to the following:

```
## Week at a Glance
![[{{monday:gggg-MM-DD}}]]
![[{{tuesday:gggg-MM-DD}}]]
![[{{wednesday:gggg-MM-DD}}]]
![[{{thursday:gggg-MM-DD}}]]
![[{{friday:gggg-MM-DD}}]]
![[{{saturday:gggg-MM-DD}}]]
![[{{sunday:gggg-MM-DD}}]]
```

Let me know if that fixes the issue you're seeing!

And I'll update the README to make that more clear.

**Comment by scotnewbury** [comment]
@liamcain That was it, an oversight on my part. Thanks for catching it for me.
