### ISSUE TITLE
Calender does not fit sidebar when "Show week number" is enabled

### ISSUE THREAD

**Issue by henrikfalk** [liamcain/obsidian-calendar-plugin#109]
Calendar v. 1.4.13

### Describe the bug
Calender does not fit sidebar when "Show week number" is enabled

### Steps to reproduce

See: 
![Screenshot_20210118_071154](https://user-images.githubusercontent.com/30142914/104879012-4aff2d80-595d-11eb-841b-2f32ae7a82bb.png)

### Expected behavior

Calendar should fit sidebar both when  "Show week number" is enabled or not

### Screenshots

![Screenshot_20210118_071154](https://user-images.githubusercontent.com/30142914/104879012-4aff2d80-595d-11eb-841b-2f32ae7a82bb.png)

#### OS

Linux Manjaro, Danish language

#### Obsidian Version (e.g. v0.10.6)

Obsidian v. 0.10.7

**Comment by ShreyasKallingal** [comment]
You have to click and drag the pane to be wider I believe.

**Comment by henrikfalk** [comment]
Ah, stupid me :)
I never tried to resize the sidepanel, ha ha 
and Obisidan actually remembers the width...
