### ISSUE TITLE
Add option to start week on Monday

### ISSUE THREAD

**Issue by argenos** [liamcain/obsidian-calendar-plugin#11]

**Comment by dariuszkowalski-com** [comment]
+1  In my country (Poland) a week starts on Monday

**Comment by mrjackphil** [comment]
Came here for this one 👍

**Comment by liamcain** [comment]
Added this setting in v1.2.0, let me know if there are any issues!

**Comment by ngirard** [comment]
@liamcain, works like a charm... Thanks !
