### ISSUE TITLE
Blank setting and sidebar

### ISSUE THREAD

**Issue by Gadwood** [liamcain/obsidian-calendar-plugin#119]
> **Before Submitting:** Double-check that you are running the latest version of the plugin. The bug might have already been fixed 😄

### Describe the bug
Hello, just to let you know that i just updated my obsidian to v0.10.9 and the calendar tab stay empty and also the setting page is blank.

Thank you
![Capture d’écran, le 2021-01-21 à 16 07 03](https://user-images.githubusercontent.com/69422318/105412428-bae21200-5c02-11eb-8ea5-db8d0eeafedb.png)
![Capture d’écran, le 2021-01-21 à 16 07 29](https://user-images.githubusercontent.com/69422318/105412453-c59ca700-5c02-11eb-83ca-20e56662e281.png)

_A clear and concise description of what the bug is._

### Steps to reproduce

3. See error

### Expected behavior

_A clear and concise description of what you expected to happen_.

### Screenshots

_If applicable, add screenshots to help explain your problem._

#### OS

[macOS]

#### Obsidian Version (e.g. v0.10.6)

v0.10.9

### Theme (if applicable):

Tried to change theme and did not work. I'm on "Atom" them

**Comment by liamcain** [comment]
Uh oh! That doesn't look right, sorry about that. 

To help track down what went wrong, could you screenshot what you seen in the Developer tools? `command + shift + i` should open it, then just screenshot whenever is in the "Console" tab.

![image](https://user-images.githubusercontent.com/693981/105413214-cbdf5300-5c03-11eb-8110-3ff89ee023bf.png)

**Comment by Gadwood** [comment]
Hummm cmd + shift + i does nothing :S

Guillaume Gadbois-Gervais
Télécommunications Grimard inc.

De : Liam Cain <notifications@github.com>
Répondre à : liamcain/obsidian-calendar-plugin <reply@reply.github.com>
Date : jeudi 21 janvier 2021 à 16:15
À : liamcain/obsidian-calendar-plugin <obsidian-calendar-plugin@noreply.github.com>
Cc : Gadwood <guillaume@gadbois.cc>, Author <author@noreply.github.com>
Objet : Re: [liamcain/obsidian-calendar-plugin] Blank setting and sidebar (#119)


Uh oh! That doesn't look right, sorry about that.

To help track down what went wrong, could you screenshot what you seen in the Developer tools? command + shift + i should open it, then just screenshot whenever is in the "Console" tab.

[Image supprimée par l'expéditeur. image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F693981%2F105413214-cbdf5300-5c03-11eb-8110-3ff89ee023bf.png&data=04%7C01%7C%7Cd45f7475b9cb44b5393c08d8be51b3d9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637468605399486574%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AKalXWIzPiOXX%2Buoq2CrJqqa%2BBCBhxZGcX069nmQTug%3D&reserved=0>

**Comment by liamcain** [comment]
@Gadwood, sorry I mistyped. I meant to say `command + option + i`. You can also open the Developer Tools from the View menu here: 
![image](https://user-images.githubusercontent.com/693981/105516132-85413580-5ca3-11eb-9fe5-a43e800d2ce6.png)

**Comment by Gadwood** [comment]
[cid:image001.png@01D6F0B5.332BBEA0]

Guillaume Gadbois-Gervais
Télécommunications Grimard inc.

De : Liam Cain <notifications@github.com>
Répondre à : liamcain/obsidian-calendar-plugin <reply@reply.github.com>
Date : vendredi 22 janvier 2021 à 11:21
À : liamcain/obsidian-calendar-plugin <obsidian-calendar-plugin@noreply.github.com>
Cc : Gadwood <guillaume@gadbois.cc>, Mention <mention@noreply.github.com>
Objet : Re: [liamcain/obsidian-calendar-plugin] Blank setting and sidebar (#119)


@Gadwood<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGadwood&data=04%7C01%7C%7Cd9aa9c977f35439a31a508d8bef1d747%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637469293190595418%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kDzUnZjIRenPJh7rM5JjYa03XX3UfxYgj%2FZ21fzoHH8%3D&reserved=0>, sorry I mistyped. I meant to say command + option + i. You can also open the Developer Tools from the View menu here:
[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F693981%2F105516132-85413580-5ca3-11eb-9fe5-a43e800d2ce6.png&data=04%7C01%7C%7Cd9aa9c977f35439a31a508d8bef1d747%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637469293190605414%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3SxBQ7l2S8WKZ4%2F7JhH%2B466pvM%2Fey4HlC%2F9drwVHi1s%3D&reserved=0>

**Comment by liamcain** [comment]
Hi, could you post the image from github? It doesn't show up when you send the image via email.

**Comment by Gadwood** [comment]
![Capture d’écran, le 2021-01-22 à 11 53 02](https://user-images.githubusercontent.com/69422318/105528303-d1e03d00-5cb2-11eb-89e8-760eaf9a2bb7.png)

**Comment by liamcain** [comment]
@Gadwood, the problem seems to be that the plugin can't find your Daily Notes folder (set from the Daily Notes plugin settings). The plugin definitely should have handled that better so I just released v1.4.17 which will just display an error message in that case.

I recommend double checking your Daily Note plugin settings and making sure that the folder path is configured correctly. If you think it is configured correctly and the calender plugin is just failing to find it, let me know. I can take a closer look.

**Comment by Gadwood** [comment]
It works well now thank you very much.

Have a nice day

Guillaume Gadbois-Gervais
Télécommunications Grimard inc.

De : Liam Cain <notifications@github.com>
Répondre à : liamcain/obsidian-calendar-plugin <reply@reply.github.com>
Date : vendredi 22 janvier 2021 à 17:28
À : liamcain/obsidian-calendar-plugin <obsidian-calendar-plugin@noreply.github.com>
Cc : Gadwood <guillaume@gadbois.cc>, Mention <mention@noreply.github.com>
Objet : Re: [liamcain/obsidian-calendar-plugin] Blank setting and sidebar (#119)


Reopened #119<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fliamcain%2Fobsidian-calendar-plugin%2Fissues%2F119&data=04%7C01%7C%7Cc0fc7e1efa114382f4e208d8bf24ff81%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637469512908601976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=W7B%2B9TA7A3suFiC5diQFCwHALWDMCmxZVYPABF5T%2BKc%3D&reserved=0>.
