### ISSUE TITLE
Cannot create dailynote correctly

### ISSUE THREAD

**Issue by Quorafind** [liamcain/obsidian-calendar-plugin#12]
Operating System: Win10

What I wanted to see: When I clicked the button to create a daily note of one day, it could generate the daily note well. 

What I saw: When I clicked the button, an error message appeared in the console:

```
Uncaught (in promise) Error: File name cannot contain any of the following characters: * " \ / < > : |
```

What I changed on the Daily note plugin:

![image](https://user-images.githubusercontent.com/13215013/97720575-63507080-1b03-11eb-88ff-15ce28af40d1.png)

When I changed the default format of dailynote or changed the default storage location of dailynote, this bug would appear.

**Comment by liamcain** [comment]
This should be fixed as of v1.1.3.
