### ISSUE TITLE
Some related bugs: Using another language than English confuses/breaks the plugin

### ISSUE THREAD

**Issue by henrikfalk** [liamcain/obsidian-calendar-plugin#121]
Plugin version: 1.4.17
Obsidian v0.10.10

I have used the plugin some time now and English as language and everything works fine.
But when I changed to Danish language today I have found two issues:

I use the following date format in the "Daily notes" plugin: "DD. MMMM YYYY" which how you write dates in Danish.

### Describe the bug
When I click on a date and no note is found I get the following dialog:
![Screenshot_20210125_181739](https://user-images.githubusercontent.com/30142914/105741322-71633100-5f3a-11eb-9515-ddd4b6b578b3.png)
Then it creates a note with name of the date in the correct format ex. "26. januar 2021".
Bug: You cannot see any dots in the calender indicating that it has content even though it has.
Bug: If I later click on the same date in the calendar I get the same create dialog and if I choose "create" it fails, because the file exists. It should open the note "26. januar 2021" because it exists.
Bug: If I select an older date with notes in the Calendar created with English locale ("19. January 2021") it opens the file: "19. January 2021" which it shouldn't. It should try to open a file called: "19. januar 2021".

It seems as the plugin internally uses the English locale.
The plugin creates the correct localized filenames but cannot read them.

PS. I know I have to rename the old files with English datenames to Danish datenames when the plugin reads localized filenames correct..

**Comment by liamcain** [comment]
Hi @henrikfalk, thanks for the detailed bug report! I was able to reproduce the issue and track down what was happening. I just published v1.4.19 which will now keep the localization in sync, so things should be working as expected.

Let me know if you are still running into any issues after updating!

---

> PS. I know I have to rename the old files with English datenames to Danish datenames when the plugin reads localized filenames correct..

Yeah, sorry about that. It would be cool if the plugin offered to do the renames automatically though!
