### ISSUE TITLE
Feature Req: command for moving sequentially through daily notes

### ISSUE THREAD

**Issue by dsteinbock** [liamcain/obsidian-calendar-plugin#124]
For a keyboard-driven workflow, it would be oh-so-helpful to be able to browse daily notes sequentially through time w/ backward and forward hotkeys.

My feature request: implement sequential browsing as hotkey-assignable Obsidian commands. The hotkeys would skip over days with no daily note file.

**Comment by liamcain** [comment]
Hi @dsteinbock, this should already be possible using the commands provided by the Daily Notes plugin: 
![image](https://user-images.githubusercontent.com/693981/106357725-dc638d80-62d5-11eb-8497-9a19361cb67d.png)

**Comment by dsteinbock** [comment]
Oh, you are right, thank you. I tried to find that function by searching the command palette. I assumed the hotkey and command palette lists would be identical. I guess they are not. Strange.
