### ISSUE TITLE
Creating weekly note for first week uses the year 2021

### ISSUE THREAD

**Issue by rainydevbs** [liamcain/obsidian-calendar-plugin#126]
Using Calendar version 1.4.19

### Describe the bug

Creating a weekly note for the first week of a year creates a note using the following year. #86 is the same issue, but closed. I created a new issue, so it wouldn't have to be reopened manually. Wasn't sure what y'all would prefer.

### Steps to reproduce
Prerequisites:
- Use weekly note format that includes year. Screenshot uses format `gggg-MM-DD [Week] ww`
1. Click on week 1 in 2020
2. Observe created note's name with the year 2021

### Expected behavior
Use the correct year for the note's name

### Screenshots
![image](https://user-images.githubusercontent.com/10121527/106344329-911a9200-6277-11eb-87a1-32e142b00d6e.png)
First week of January 2021 shows this:
![image](https://user-images.githubusercontent.com/10121527/106344341-95df4600-6277-11eb-8fa5-2ff2a4cc3bc7.png)

![image](https://user-images.githubusercontent.com/10121527/106344412-ca530200-6277-11eb-94c7-305b1ce90a5c.png)
![image](https://user-images.githubusercontent.com/10121527/106344431-e2c31c80-6277-11eb-8fda-887f864e9c4b.png)

#### OS

Windows

#### Obsidian Version (e.g. v0.10.6)
Obsidian v0.10.11

**Comment by liamcain** [comment]
Hi @rainydevbs! I think the issue here is that you're using `gggg` in your format for the year. `gggg` refers to the Locale Week Year. In other words, that's "Week 1 of 2021." Since it looks like you want to name the weekly notes based on Sunday of the week, you probably want to use the format: `YYYY-MM-DD [Week] ww`. That will give you `2020-12-27 Week 01`.

**Comment by rainydevbs** [comment]
Thanks for the quick catch! That was indeed the issue. Switching to `YYYY` over `gggg` is now giving me the following: 
![image](https://user-images.githubusercontent.com/10121527/106345463-5700be80-627e-11eb-9af4-9d5425a8c8dc.png)
