### ISSUE TITLE
The "show week number" shows wrong week number in 2021

### ISSUE THREAD

**Issue by gh16683170** [liamcain/obsidian-calendar-plugin#128]
> **Before Submitting:** Double-check that you are running the latest version of the plugin. The bug might have already been fixed 😄

### Describe the bug
The week number in 2021-01-01 ~ 2021-01-03 should be  "1", but now it shows "53"(count start from year 2020)
_A clear and concise description of what the bug is._

### Steps to reproduce
1. Enable "show week number" in "General Settings"
2. The week number in 2021-01-01 ~ 2021-01-03 should be show "1", but now it shows "53"(count start from year 2020)
### Expected behavior
show the right week numer in 2021
_A clear and concise description of what you expected to happen_.

### Screenshots
![image](https://user-images.githubusercontent.com/16650849/107193030-5956db80-6a29-11eb-86a0-fa84feb639fd.png)

_If applicable, add screenshots to help explain your problem._

#### OS
windows
[Windows/macOS/Linux]

#### Obsidian Version (e.g. v0.10.6)
v0.10.12
`(Settings → About → Current Version)`

### Theme (if applicable):
Blue Topaz
_If the bug is visual, please provide the name of the Community Theme you're using._

**Comment by liamcain** [comment]
hi @gh16683170, the week numbers are determined by your locale. Most locales consider that week to be Week 53. If you want that week to be Week 1, you might need to override the locale to en-US. You can override it settings. Go to `Settings > Calendar Settings > Override Locale`.

![image](https://user-images.githubusercontent.com/693981/107323054-a069be80-6a73-11eb-9a08-1730eee2be0c.png)

You might need to restart Obsidian for the change to take effect.

**Comment by hepabolu** [comment]
@liamcain Not entirely true. 
I've had my settings set to same as system (en-us) like in the picture and it gives me the wrong week number, while all other calendar apps on my machine give the correct week number.
I've changed the locale in the screenshot above to 'en-gb' and restarted Obsidian. That helps, but it is NOT the system locale.

**Comment by liamcain** [comment]
You're right, it's a little more nuanced than that.

It's very common for other apps to default to using the ISO 8601 format for week numbering (an international standard) regardless of locale. The calendar plugin does not; it's formatting is always locale-aware. The `en-GB` locale just happens to follow the ISO 8601 standard.

---

Sounds like changing that fixed your issue. Let me know if you run into any additional trouble!
