### ISSUE TITLE
Calendar plugin causes valut to not load

### ISSUE THREAD

**Issue by jenningsb2** [liamcain/obsidian-calendar-plugin#13]
Before disabling:

![image](https://user-images.githubusercontent.com/29644050/97742548-d08be380-1aba-11eb-925e-8636d8c0a50f.png)

After disabling

![image](https://user-images.githubusercontent.com/29644050/97742570-d8e41e80-1aba-11eb-8bdb-84059da44dbc.png)

**Comment by liamcain** [comment]
@jenningsb2 hi, is there any chance you have a very large daily note in your vault?

**Comment by jenningsb2** [comment]
Hmm I don’t think so... my largest file is 15kb.

**Comment by liamcain** [comment]
This should be fixed as of v1.1.3. Let me know if the issue persists and I'll reopen the ticket!
