### ISSUE TITLE
Possibility to choose the language independent of system language?

### ISSUE THREAD

**Issue by RankkaApina** [liamcain/obsidian-calendar-plugin#130]
So, I made this feature (not in a pretty way) to the previous version. I did it because I like studying languages and I liked the calendar to reflect that language, especially since the language is Basque and I've been having such a hard time to learn the months and weekdays. However, I don't want to change my system language, because that just makes my life unnecessarily hard. I could switch the Obsidian language, but it doesn't exist in Basque. My solution (while not pretty coding wise) worked perfectly and then I updated to the newest version of the plugin and you've changed how to do this. 

Of course I can try to figure this out on my own (and I probably will), but I was wondering if this was something that could be integrated in the plugin? Even if you don't want to work on it, but if I find a more elegant solution, I could give you the piece of code to add it? I do get that this might be bit of a niche request... But I'd like to keep updating the plugin without extra effort (especially since I don't think you constantly change the way the reading of the locale works).

**Comment by liamcain** [comment]
In settings, there is an option to override the default locale. If I understand the request, that should work for your usecase:
![image](https://user-images.githubusercontent.com/693981/107323054-a069be80-6a73-11eb-9a08-1730eee2be0c.png)

**Comment by RankkaApina** [comment]
Thank you, yes! I don't know how I missed that!!! Makes my life so much easier :)
