### ISSUE TITLE
New note daily based on template with {{tp_title}} creates wrong title if another note is sticky

### ISSUE THREAD

**Issue by henrikfalk** [liamcain/obsidian-calendar-plugin#133]
Obsidian v0.11.0

Just found a strange bug.

I have a template for daily notes using "# Daglige noter - {{tp_title}}" as the first line in the note.

If I have a sticky note the Calender plugin creates a new daily note and expanding {{tp_title}} with the title of the sticky note and not the name of the daily note.

Example ho to produce issue:
1. I have a sticky note names "Hello" opened in a panel
2. I click on a date in the Calendar which does not have a daily note
3. The dialog appear with the correct name ex. "11. februar 2021" and creates the correct filename for the daily note
4. But the first line is "# Daglige noter - Hello" and not "# Daglige noter - 11. februar 2021" which should be expected because I use {{tp_title}}

A workaround is to make any notes unsticky before selecting a date in the calendar for a new daily note. Then it works.

/Henrik :)

**Comment by liamcain** [comment]
Hi @henrikfalk, this sounds like a bug with the Templater plugin and out of the control of the Calendar plugin.

I recommend creating the issue on that repo instead: https://github.com/SilentVoid13/Templater

That said, you shouldn't need the Templater plugin for this, you should be able to just use `{{title}}`

**Comment by henrikfalk** [comment]
Thanks :)
You are right.
I close this issue.
