### ISSUE TITLE
Slowdown obsidian and link week 6 to a PDF

### ISSUE THREAD

**Issue by Gadwood** [liamcain/obsidian-calendar-plugin#136]
### Describe the bug

When i choose to show week number obsidian become really slow and week 6 does not appear for a while and when it does it link it to a PDF into my files folder

### Screenshots

![Capture d’écran, le 2021-02-11 à 20 16 37](https://user-images.githubusercontent.com/69422318/107719371-10f82180-6ca6-11eb-830c-e8afced6605e.png)
![Capture d’écran, le 2021-02-11 à 20 16 21](https://user-images.githubusercontent.com/69422318/107719376-15243f00-6ca6-11eb-8cb4-fd33f7eca442.png)

#### OS

macOS

#### Obsidian Version 

v0.11.0
calendar 1.5.1

### Theme (if applicable):

Molecule

**Comment by liamcain** [comment]
Thanks for quick report, sounds like a bug I introduce with the change in 1.5.1. Sorry about that.

To help debug, could you share your Weekly Note format? Also, If it's not personal/sensitive info, do you mind sharing the filename for the PDF that gets opened?

The plugin seems to be getting confused and thinking the PDF is a weekly note.

**Comment by liamcain** [comment]
This should be fixed in version 1.5.2, let me know if you're still running into issues!

**Comment by Gadwood** [comment]
Fixed thank you


​_____________________

Guillaume Gadbois Gervais

514.419.3382 | 514.863.6659 (cell)

Rosemont, Montréal Qc
guillaume@gadbois.cc

________________________________
De : Liam Cain <notifications@github.com>
Envoyé : 12 février 2021 09:19
À : liamcain/obsidian-calendar-plugin <obsidian-calendar-plugin@noreply.github.com>
Cc : Gadwood <guillaume@gadbois.cc>; Author <author@noreply.github.com>
Objet : Re: [liamcain/obsidian-calendar-plugin] Slowdown obsidian and link week 6 to a PDF (#136)


This should be fixed in version 1.5.2, let me know if you're still running into issues!
