### ISSUE TITLE
Weekly note creation off-by-one

### ISSUE THREAD

**Issue by jellopuddingstick** [liamcain/obsidian-calendar-plugin#140]
### Describe the bug

Selecting a blank week number creates a note for the previous week (e.g. clicking `8` creates `2021-W07`).

Selecting a blank week number shows "Unable to create a new file" if the previous week has a note.

However, if a weekly note already exists, the dot appears on the correct number, and clicking it opens the correct note.

### Steps to reproduce

1. Install Calendar and Periodic Notes plugins
2. Configure according to following settings
3. Click week number on calendar

**Calendar `data.json`**
```json
{
  "shouldConfirmBeforeCreate": false,
  "weekStart": "sunday",
  "wordsPerDot": 250,
  "showWeeklyNote": true,
  "weeklyNoteFormat": "",
  "weeklyNoteTemplate": "",
  "weeklyNoteFolder": "",
  "localeOverride": "en-gb"
}
```

**Periodic Notes `data.json`**
```json
{
  "showGettingStartedBanner": false,
  "hasMigratedDailyNoteSettings": false,
  "hasMigratedWeeklyNoteSettings": false,
  "daily": {
    "format": "YYYY-MM-DD_ddd",
    "template": "assets/templates/daily_note.md",
    "folder": "captains_log/daily",
    "enabled": true
  },
  "weekly": {
    "format": "GGGG-[W]WW",
    "template": "",
    "folder": "captains_log/weekly",
    "enabled": true
  },
  "monthly": {
    "format": "",
    "template": "",
    "folder": ""
  }
}
```

### Expected behavior

Selecting a week number should create or open the weekly note with the same number.

### Screenshots

![Screen Shot 2021-02-16 at 11 07 04 AM](https://user-images.githubusercontent.com/5808956/108097011-39d23b00-7047-11eb-9159-1bb73ef2924d.png)

```shell
captains_log
├── daily
│   ├── 2021-02-01_Mon.md
│   ├── 2021-02-08_Mon.md
│   ├── 2021-02-09_Tue.md
│   ├── 2021-02-10_Wed.md
│   ├── 2021-02-11_Thu.md
│   ├── 2021-02-12_Fri.md
│   └── 2021-02-16_Tue.md
└── weekly
    └── 2021-W06.md
```

As you can see, the `2021-W06` note correctly results in a dot on ISO week 6. However, clicking the other week numbers produce the error described.

#### OS

macOS

#### Obsidian Version (e.g. v0.10.6)

v0.10.13

### Theme (if applicable):

Obsidian gruvbox

**Comment by liamcain** [comment]
Hi @jellopuddingstick, the calendar renders the week numbers using the locale week number (rather than the ISO week number). To keep them in sync, your weekly note format should be `gggg-[W]ww`. Since you have the locale override configured to en-GB, I _think_ it should still produce the same week numbers you're seeing.

Let me know if that works for your use case!

**Comment by jellopuddingstick** [comment]
Hey @liamcain, thanks for the quick response. It does appear that `gggg-[W]ww` works. I think the issue actually involved setting `"weekStart": "sunday"` as well, since disabling that made it work correctly with `GGGG-[W]WW`.

Regardless the following settings seem to work for me, so thanks!

## Calendar `data.json`
```json
{
  "shouldConfirmBeforeCreate": false,
  "weekStart": "sunday",
  "wordsPerDot": 250,
  "showWeeklyNote": true,
  "weeklyNoteFormat": "",
  "weeklyNoteTemplate": "",
  "weeklyNoteFolder": "",
  "localeOverride": "en-gb"
}
```

## Periodic Notes `data.json`
```json
{
  "showGettingStartedBanner": false,
  "hasMigratedDailyNoteSettings": false,
  "hasMigratedWeeklyNoteSettings": false,
  "daily": {
    "format": "YYYY-MM-DD_ddd",
    "template": "assets/templates/daily_note.md",
    "folder": "captains_log/daily",
    "enabled": true
  },
  "weekly": {
    "format": "gggg-[W]ww",
    "template": "",
    "folder": "captains_log/weekly",
    "enabled": true
  },
  "monthly": {
    "format": "",
    "template": "",
    "folder": ""
  }
}
```
