### ISSUE TITLE
Timeboxing

### ISSUE THREAD

**Issue by broskees** [liamcain/obsidian-calendar-plugin#142]
> **Before Submitting:** Double-check that you are running the latest version of the plugin. The feature might have already been included 😄

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I'd like to see time-boxing view under the calendar like [Noteplan](https://noteplan.co/). +1 if it integrates with iCal. 

**Describe alternatives you've considered**

Downloading Noteplan itself, don't want to manage multiple vaults though and it the "same vault" options seem to have a good risk of data lass.

**Additional context**

Specifically I'm talking about this view:
<img width="216" alt="Screen Shot 2021-02-16 at 11 59 47 PM" src="https://user-images.githubusercontent.com/18671860/108158832-c286c080-70b3-11eb-8457-5eb29aaff4eb.png">
It works by placing a timeframe string (2p-4p) next to a task, which would add it to this list. I'm not sure if this actually creates a task in your calendar, but in the app, it displays there.

**Comment by liamcain** [comment]
Hi, @broskees, you might be interested in the Day Planner plugin (https://github.com/lynchjames/obsidian-day-planner). It provides a similar functionality to what you're after.

**Comment by broskees** [comment]
Wow, thanks for that share!

**Comment by liamcain** [comment]
Since I think this feature is out of scope for the calendar plugin and there's an existing plugin providing similar functionality, I'm going to close this request.
