### ISSUE TITLE
Feature Request: Opening existing note from Calendar pane use default view mode.

### ISSUE THREAD

**Issue by MikeBraddock** [liamcain/obsidian-calendar-plugin#147]
**Is your feature request related to a problem? Please describe.**
I want to open existing notes from the Calendar plugin's pane in Preview mode instead of edit mode. I have the default view mode in the Obsidian Editor settings set to preview. When using the Calendar pane links, they open in the last mode I used before clicking Calendar links for existing notes.

**Describe the solution you'd like**
I want the calendar pane to use the default view mode I have set in the Obsidian Editor settings to default on how links open from the calendar pane for existing notes. 

<img width="1108" alt="2021-03-07 09-05-13 Sunday screenshot" src="https://user-images.githubusercontent.com/80207517/110244324-32a69a80-7f2c-11eb-8cee-84beb4936612.png">

**Describe alternatives you've considered**
An alternative could be an additional Calendar plugin setting that sets the default view for links opened from the Calendar plugin pane for existing notes. 

**Additional context**
Great plugin! Thank you for your hard work.

**Comment by liamcain** [comment]
Good point! I added this to v1.5.4
