### ISSUE TITLE
Customize daily progress indicator

### ISSUE THREAD

**Issue by akicebear** [liamcain/obsidian-calendar-plugin#15]
It isn't clear to me what dots represent - every 100 words? In any case, I'd like if I could define a daily target (e.g. 1000 words).

Not sure how feasible it is, but it'd be nice if there was a filled percentage of each box (e.g. box is blank normally, fills with white) as it nears the target. Even absent this, defining the words per dot would be nice.

**Comment by liamcain** [comment]
This is a cool idea. I like the idea of defining a daily target a lot!
