### ISSUE TITLE
Delete note  from Calendar view Doesn't work

### ISSUE THREAD

**Issue by danieltomasz** [liamcain/obsidian-calendar-plugin#150]
> **Before Submitting:** Double-check that you are running the latest version of the plugin. The bug might have already been fixed 😄

### Describe the bug
When trying to delete an existing note clicking on it in the calendar view>Delete nothing happens
_A clear and concise description of what the bug is._

### Steps to reproduce

1. Go to Calendar View
2. Click on 'Note>Delete
3. Nothing happens 
4. Console error:
```
app.js:1 Uncaught TypeError: Cannot read property 'length' of undefined
    at e.promptForFolderDeletion (app.js:1)
    at eval (eval at evalFunc (app.js:1), <anonymous>:4146:25)
    at HTMLDivElement.<anonymous> (app.js:1)
```

### Expected behaviour
The note will be deleted (same way as in clicking on it in Folder view)
_A clear and concise description of what you expected to happen_.

### Screenshots

_If applicable, add screenshots to help explain your problem._

#### OS

[Windows/macOS/Linux]

#### Obsidian Version (e.g. v0.10.6)
Obsidian 0.11.5
Calendar 1.5.3
Linux PopOS 20.10
`(Settings → About → Current Version)`

### Theme (if applicable):

_If the bug is visual, please provide the name of the Community Theme you're using._

**Comment by liamcain** [comment]
Good catch, this should be fixed in v1.5.4!
