### ISSUE TITLE
Show page preview on hover

### ISSUE THREAD

**Issue by arminta7** [liamcain/obsidian-calendar-plugin#154]
It would be really neat to be able to preview daily notes by hovering over the date on the calendar!

**Comment by liamcain** [comment]
You can already do this if you have the "Page Preview" core plugin enabled. Just hover over the day while holding the "meta" key (so `command` on MacOS and `control` on Windows.

**Comment by arminta7** [comment]
Awesome! It was the 'command' key that I was missing. Thanks!
