### ISSUE TITLE
Click on day without file existing does not do anything - throws "Folder already existing" error on console

### ISSUE THREAD

**Issue by bietiekay** [liamcain/obsidian-calendar-plugin#157]
After the latest update (today) I cannot click on days that do not yet have a daily file and have it create that file for me. It basically just yields a "Folder already exists" message on the console and does not display any error to the user.

This is on desktop with the most current obsidian public version.

Downgrading to an earlier version of the calendar plug-in does restore the "create new daily" functionality for me.

**Comment by psidnell** [comment]
Having the same issue (new user, clean install)

**Comment by liamcain** [comment]
Hi thanks for the quick report @bietiekay! I just published a new version with the fix. Sorry about that.

**Comment by bietiekay** [comment]
works! Thanks a lot for the quick fix!
