### ISSUE TITLE
Unable to create new weekly note by selecting week number in calendar

### ISSUE THREAD

**Issue by jtmusky** [liamcain/obsidian-calendar-plugin#159]
Selecting the weekly note from the calendar, prompts to create a "New Weekly Note". Stating the file does not exist. Unable to create the file.

Below is the screenshot of the prompt and the "uncaught" error. Something about folder already exists.

This is what I have for my Daily and Weekly configuration.

```
Daily
format: [5 📝 Journal]/YYYY/MM/YYYY-MM-DD
Note Folder: /

Weekly
format: [5 📝 Journal]/YYYY/[W]/YYYY-[W]ww
Note Folder: /
```

<img width="550" alt="Screen Shot 2021-03-21 at 11 24 25 PM" src="https://user-images.githubusercontent.com/23535616/111940492-dcde0080-8a9c-11eb-8620-234d00d65ce5.png">
<img width="500" alt="Screen Shot 2021-03-21 at 11 22 52 PM" src="https://user-images.githubusercontent.com/23535616/111940498-df405a80-8a9c-11eb-9ff5-d050984ed667.png">

**Comment by liamcain** [comment]
This was an issue with the latest version of the Calendar plugin so I moved the issue to this repository instead. But the issue should be fixed if you update your Calendar plugin version to v1.5.7. Sorry about that!

**Comment by jtmusky** [comment]
No worries! I am just grateful that this plugin exists at all! thank you

-JM
