### ISSUE TITLE
Doesn't recognize existing daily notes

### ISSUE THREAD

**Issue by ngirard** [liamcain/obsidian-calendar-plugin#16]
Using calendar plugin v1.1.3 / Obsidian 0.9.10 / Ubuntu 12.04.

My daily notes settings are as follows:
![image](https://user-images.githubusercontent.com/98098/97786020-ed064980-1ba8-11eb-912c-d1a4e0e32e4d.png)

Once the calendar plugin is displayed, clicking on a 2020-10-30 leads to this warning:
![image](https://user-images.githubusercontent.com/98098/97786061-38b8f300-1ba9-11eb-8d8f-c0c6f412d102.png)

The note for that day does exists; its path relative to the root vault is `j/2020-10-30 Fri.md`, as can be deduced from the daily notes settings.

**Comment by AJP4** [comment]
I still have the same problem.
Click on a date in the future give me the pop-up below but pressing the Create button does nothing (Never Mind button works ok, but I guess it doesn't have much to do).

![image](https://user-images.githubusercontent.com/7826593/97791956-f2c35580-1bcf-11eb-81eb-85a6455248b9.png)


Daily Note set-up looks like this if it helps

![image](https://user-images.githubusercontent.com/7826593/97791968-17b7c880-1bd0-11eb-904a-28523e6e5f55.png)

**Comment by liamcain** [comment]
@ngirard Hi, thanks for the report. The plugin was previously having trouble finding the daily note settings on Linux. I updated how I find the settings in version 1.1.4, could you check to see if the issue still persists after updating?

**Comment by ngirard** [comment]
It's working just fine now.
Thanks for your work !
Closing as fixed.
