### ISSUE TITLE
Fantasy Calendar

### ISSUE THREAD

**Issue by rmasoni** [liamcain/obsidian-calendar-plugin#165]
**Is your feature request related to a problem? Please describe.**
As a Dungeon Master/worldbuilder, I'd like to have my custom fantasy calendar integrated with the rest of the documents.

**Describe the solution you'd like**
Ability to customize eras, years, months and weekdays' names and numbers. For example, my world uses 12-month, 24-day, 6-weekday years divided in eras (which reset the year count).

**Describe alternatives you've considered**
I tried using a separate service called [Fantasy Calendar](https://fantasy-calendar.com), but it's cumbersome to switch to the browser during game sessions as the time progresses and I often forget.

**Additional context**
This is probably a big stretch and could perhaps be an entirely separate plugin, but I thought it was worth suggesting.

**Comment by liamcain** [comment]
Hi @rmasoni, I haven't looked too far into it but this might be pretty tricky. Currently the plugin leverages [`moment.js`](momentjs.com) for the date handling and I'm not sure it supports that level of customization.

I'll need to do some experimentation to see.

**Comment by Dmitriy-Shulha** [comment]
It looks like Fantasy Calendar was already integrated into Obsidian in [this new plugin](https://github.com/valentine195/obsidian-fantasy-calendar). And AFAIK, it even supports import from website.

**Comment by liamcain** [comment]
Closing since the Fantasy Calendar already fits this use case perfectly. No need to compete.
