### ISSUE TITLE
Filenames can be date followed by any text

### ISSUE THREAD

**Issue by leoplanet** [liamcain/obsidian-calendar-plugin#167]
> **Before Submitting:** Double-check that you are running the latest version of the plugin. The feature might have already been included 😄

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by liamcain** [comment]
Hi @leoplanet, I'm just going to close this in favor of #39 which is requesting the same feature. Feel free to +1 that to show your interest and help me prioritize.
