### ISSUE TITLE
Current date only changes on refresh/reload

### ISSUE THREAD

**Issue by fitzagard** [liamcain/obsidian-calendar-plugin#17]
Great work on this plugin! I came across a minor issue. If Obsidian remains open (I tend to never close it) it seems like the active day will not change.  After a quick look, it appears that `const today = (window as any).moment();` isn't refreshed at all. Maybe a refresh when using the Open today's Note keystroke could do the trick to always show the active day.

**Comment by liamcain** [comment]
Oh, wow! Nice find. I'll add a heartbeat to keep this in sync with the time.

**Comment by liamcain** [comment]
Added this in v1.1.6! Also, if it's midnight on the last day of the month, it will update to show the new month.
