### ISSUE TITLE
Calendar: styles.css not found

### ISSUE THREAD

**Issue by mscrim** [liamcain/obsidian-calendar-plugin#170]
### Describe the bug

Looks like a css file is missing. The following error shows up in the Obsidian Developer Console:

`Failed to load resource: the server responded with a status of 404 () https://github.com/liamcain/obsidian-calendar-plugin/releases/download/1.5.10/styles.css `
`Calendar: styles.css not found`

Thanks for the great plugin!

**Comment by liamcain** [comment]
Thanks for the heads up! The error is harmless since Obsidian will always look for a `styles.css` file even if there isn't one. It shouldn't effect the plugin at all though.
