### ISSUE TITLE
Can't open daily note

### ISSUE THREAD

**Issue by zhxrrb** [liamcain/obsidian-calendar-plugin#171]
> **Before Submitting:** Double-check that you are running the latest version of the plugin. The bug might have already been fixed 😄

### Describe the bug
Cannot open existing daily note. Create a daily note file by clicking on a day of the calender view without an existing file, then clicking on the same day won't open the file either. And it prompts "Unable to create  new file"
### Steps to reproduce

3. See error

### Expected behavior

_A clear and concise description of what you expected to happen_.

### Screenshots
![image](https://user-images.githubusercontent.com/41381435/113746048-77df0780-9738-11eb-93f9-a58fdae09de6.png)

#### Windows

[Windows/macOS/Linux]

### Theme (if applicable): 

_If the bug is visual, please provide the name of the Community Theme you're using._

**Comment by liamcain** [comment]
Hi @zhxrrb, sorry to hear your running into trouble with the plugin. To figure out what went wrong could you send me two things?
- A screenshot of your daily note settings
- A screenshot of the `Devtools > Console` after you try to create a note

The devtools should show a more complete error message with what went wrong and why it's not finding your notes correctly.

---

### How to open the developer tools

#### On MacOS

Press <kbd>Command</kbd> <kbd>Shift</kbd> <kbd>I</kbd>

#### On Windows
Press <kbd>Control</kbd> <kbd>Shift</kbd> <kbd>I</kbd>

<img width="456" alt="where-is-devtools" src="https://user-images.githubusercontent.com/693981/113791679-2facee80-9712-11eb-984d-af61520a7ac6.png">

**Comment by zhxrrb** [comment]
Here is the daily note setting.
![image](https://user-images.githubusercontent.com/41381435/113797286-91f20780-9783-11eb-937d-19e661955967.png)
And I made a screen recording to show the problem. I create today's daily note using calender, then close it. Clicking today's number on calender cannot direct me to the existing file  when it already exists.
https://user-images.githubusercontent.com/41381435/113797552-13e23080-9784-11eb-8cf4-672d18d88a61.mp4

**Comment by liamcain** [comment]
Oh I see the issue. I am using a date parsing library that might not be able to interpret the `DDDo` in your date format when searching for notes matching a particular date. I'll try to fix this this afternoon. Thanks for the screenshots!

**Comment by zhxrrb** [comment]
Thanks. Actually I changed my filename format and set the `DDDo` in the yaml part of my daily note, which satisfies my needs too. By the way, calender plugin is an awesome plugin. Appreciate your work.

**Comment by justresearch547** [comment]
Hello @liamcain I too have the same issue. I click on the date but it does not open a new note. I have attached the screen shot to the daily notes setting below. 
<img width="310" alt="Screen Shot 2021-05-12 at 11 28 53 PM" src="https://user-images.githubusercontent.com/57062905/118023224-ec7e1500-b37a-11eb-9003-a447bdce9dc6.png">

**Comment by liamcain** [comment]
Hi @justresearch547, Obsidian forbids using colons in filenames `:` since it's an illegal character in many filesystems. I recommend using a different symbol such as a dash in your date format (e.g. `YYYY-MM-DD`) to avoid issues.

**Comment by justresearch547** [comment]
Thank you so so much @liamcain !! This has solved the issue!! 

P.S: Your plug in extremely helpful! Thank you so much for creating it! :)
