### ISSUE TITLE
Override locale not working

### ISSUE THREAD

**Issue by jdanielmourao** [liamcain/obsidian-calendar-plugin#172]
### Describe the bug

Despite having Override locale option to 'same as system (pt-pt)', the date is still shown in English.

### Steps to reproduce

1. Have 'Override locale' option to 'same as system' [local language being different than the one obsidian is using (obsidian is using English, system is using Portuguese)]
2. use command {{date:dddd, D MMMM YYYY}}
3. date shows as 'Wednesday, 7 April 2021'

### Expected behavior

Date should show as 'quarta-feira, 7 abril 2021' (Portuguese, language as set in my system)

**Comment by liamcain** [comment]
Oh, that's an interesting use case. I guess "same as system" is a misnomer here that option still obeys Obsidian's language preference. I guess there should be 2 options here then:
- Same as Obsidian - the current option renamed
- Same as system - prioritize the system locale over all.

Thanks for the report!

**Comment by liamcain** [comment]
In the meantime, can you find `pt-pt` in the dropdown and set it manually?
