### ISSUE TITLE
Alt+click on a date to include the link in the current note

### ISSUE THREAD

**Issue by mdelobelle** [liamcain/obsidian-calendar-plugin#176]
**Describe the solution you'd like**
I'm a heavy user of Templater + Natural Langage Dates to include dates faster in my notes.
Since I have the calendar always opened in my side bar, it would be easier to "Alt+click" on a date on the calendar which as a result could include the link to the daily (or weekly, or monthly) at the current cursor position 

**Describe alternatives you've considered**
Templater + Natural Langage Dates but it is tidious (3 steps: invoke the templater, find the right template, type the date)
 
**Additional context**

**Comment by liamcain** [comment]
Hi @mdelobelle, I think this _might_ be satisfied once v2 is released (it's currently in [beta](https://github.com/liamcain/obsidian-calendar-plugin/tree/version-2.0#instructions)). You'll be able to drag dates from the calendar into the document.

There are also some pending improvements to the NL Dates plugin which should great streamline inserting date links. I'm hoping to get all those changes released soon!
