### ISSUE TITLE
Documentation enhancement: Explain how to open calendar view

### ISSUE THREAD

**Issue by ralfw** [liamcain/obsidian-calendar-plugin#18]
I installed the plugin, no errors were reported - but I'm unable to switch to any calendar view.
There is no content menu entry on the daily notes folder, there does not seem to be a hotkey.

Would be great if the [documentation](https://github.com/liamcain/obsidian-calendar-plugin) not only showed the plugin in action but also how to actually use it.
(I'm running Obsidian 0.9.10.)

**Comment by liamcain** [comment]
@ralfw Hi, by default the calendar view will appear in the right sidebar, so make sure you have that expanded.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/693981/97807680-26ce6300-1c30-11eb-8dbf-1c2e783bb120.png">

I will make some updates to the documentation to make it more clear, as well as adding an option to the command palette to show it.

**Comment by ralfw** [comment]
Ah, great! Yes, this works.
Would be cool to get a small hint at  that in the documentation ;-)
