### ISSUE TITLE
Failure in reading daily note template

### ISSUE THREAD

**Issue by lillianhorin** [liamcain/obsidian-calendar-plugin#19]
OS: Windows 10
Obsidian Version: 0.9.10
Plugin Version: 11.7

For about the last day, I have been receiving an error that the daily note template cannot be read. I doubled checked all the settings and everything is ok. When I use Obsidian's native daily note creator button, there is no issue using the daily note template.

![image](https://user-images.githubusercontent.com/24489520/97836467-6174e180-1caa-11eb-89d9-dc79ca4d11dd.png)

![image](https://user-images.githubusercontent.com/24489520/97836665-c92b2c80-1caa-11eb-9ce9-d0cd2f1b67f0.png)

**Comment by liamcain** [comment]
Hi, sorry for the issue. For the time being you can add `.md` to the end of the template file location to fix this. I'll have a fix out for this either today or tomorrow though.

**Comment by liamcain** [comment]
Actually, this should be fixed now. @lillianhorin can you try restarting Obsidian and seeing if the issue persists?

**Comment by lillianhorin** [comment]
Fixed! Thanks so much @liamcain !
