### ISSUE TITLE
Display week number + link to related page

### ISSUE THREAD

**Issue by ngirard** [liamcain/obsidian-calendar-plugin#20]
I live by week numbers. For instance, this week's number as of 2020-11-02 is 45.

It would be useful for me if Calendar plugin would display it.

Even greater to me would be the ability to link that week number to its related page, with the ability to customize the pattern for the path of said weekly pages.

Cheers, and thanks for the fish ;-)

**Comment by liamcain** [comment]
@ngirard Thanks for the request! For context, what pattern do you use for weekly pages?

**Comment by ngirard** [comment]
Nowadays I'm using e.g. `j/20-W45.md`, where `j` is the path for journal notes as configured in the daily notes plugin, and `20` stands for `2020`.

**Comment by psyguy** [comment]
I'd like to +1 this request!

**Comment by jdbrice** [comment]
I also want to +1 this request. Please make the week note path and date format configurable!

**Comment by liamcain** [comment]
Added this in v1.3.0. Be sure to take a look at the README for instructions on how to configure your weekly notes.

[📕 Weekly Notes](https://github.com/liamcain/obsidian-calendar-plugin#weekly-notes)
