### ISSUE TITLE
Add support for nested daily-note locations (e.g. `2020/10/04.md` or `2020-10/04.md`)

### ISSUE THREAD

**Issue by jplattel** [liamcain/obsidian-calendar-plugin#21]
Hi Liam!

Thanks for this wonderful plugin! I have a feature request that doesn't have any priority so feel free to judge if you want to solve this. Here's the thing:

I'm grouping every daily note in a folder after a month is finished:

<img width="201" alt="Screenshot 2020-11-02 at 22 39 43" src="https://user-images.githubusercontent.com/517775/97922179-58444d00-1d5c-11eb-9db8-2be356ec8029.png">

The daily notes of the current month are in the root of the `daily` folder. 

After moving the notes the plugin can't seem to find the notes anymore, thus asking me to create a new one. Is this something that could be solved? It might be a hard problem to figure out the linking to each file...

**Comment by liamcain** [comment]
Hi, thanks for the feature request! This is certainly doable, but my main focus right now is to maintain compatibility with the Daily Notes plugin.

I'll likely revisit that down the road to enable more custom workflows like yours, so I'll definitely keep this in mind.
