### ISSUE TITLE
No calendar

### ISSUE THREAD

**Issue by ljantzen** [liamcain/obsidian-calendar-plugin#23]
Hi, 

This plugin looks awesome, and I have installed it on Obsidian 0.9.10.  But I am not able to get the calendar to display anywhere? 

- there is no keyboard shortcut
- there is no command in the command palette
- there is no 'Calendar' menu item in any of the pane menus

So how do I get started with this thing?

**Comment by liamcain** [comment]
Hi @ljantzen, I'll update the description soon to be more clear about how to get started. The calendar should appear immediately in the right sidebar after you activate it.

Make sure the plugin is toggled on in the "Third Party Plugins" tab in your settings menu:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/693981/98172881-21874780-1ec0-11eb-862e-08049ad68080.png">


And make sure the right sidebar is expanded: 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/693981/97807680-26ce6300-1c30-11eb-8dbf-1c2e783bb120.png">

Let me know if that helps!

(here are the proposed usage instructions I'll be adding soon: https://github.com/liamcain/obsidian-calendar-plugin/tree/dev#usage)

**Comment by liamcain** [comment]
I updated the documentation, but left me know if the calendar still isn't showing up or if something is still unclear!

**Comment by ljantzen** [comment]
No, that solved it, thank you.  I had a problem with clicking on dates in the calendar not opening the dates note, but that seemed to solve itself somehow. I will file a new issue if that problem reappears.

**Comment by liamcain** [comment]
That's great to hear!

>  I had a problem with clicking on dates in the calendar not opening the dates note, but that seemed to solve itself somehow. 

That was an issue with an older version of the plugin, so make sure you're using v1.2.0, and you will need to restart Obsidian for the upgrade to fully take effect.
