### ISSUE TITLE
Plugin not working with Obsidian 0.9.10

### ISSUE THREAD

**Issue by hooksoft** [liamcain/obsidian-calendar-plugin#24]
I love the idea of this plugin, but.. its doing "nothing" for me on Win 10 Obsidian 0.9.10  - I click the days and nothing happens.
Am I missing something? 
I saw no mention of this 0.9.10 release on their Twitter - so I was pleasantly surprised to be able to run 3rd party plugins today :)

**Comment by liamcain** [comment]
Hi @hooksoft, I'm sorry to hear that it's not working for you. It sounds like it's having trouble finding your daily note template.

There should be an error description in the Developer Tools' console. If you go to `View > Toggle Developer Tools` could you send me a screenshot of the error so I can investigate?

**Comment by tedblizzard** [comment]
Hi @liamcain I agree with @hooksoft ... great idea but I am getting the same result... no change.  Does it matter where we put the custom CSS?  I put it at the end.  Also, I am using the custom css theme.  Let me know if this screenshot help or if you need other information.  Thank you for this cool idea.  
![image](https://user-images.githubusercontent.com/2208182/98178596-934aaa00-1f2f-11eb-98a9-c8703c85f10e.png)

**Comment by liamcain** [comment]
Hi @tedblizzard, could you click on the "Console" in the devtools tab and send me a screenshot of that?

<img width="292" alt="image" src="https://user-images.githubusercontent.com/693981/98181628-b8103480-1ed1-11eb-9b1b-9e8856f61ee5.png">

Thanks!

**Comment by hooksoft** [comment]
Hey @liamcain , sorry for not answering earlier. Here a screenshot:

![image](https://user-images.githubusercontent.com/48322856/98189003-d76b8980-1ef2-11eb-9ac6-0fc7f5314d26.png)

**Comment by hooksoft** [comment]
I tried configuring a daily template and now it works. Sorry if that was a requirement that I missed..
(I also set a folder for Daily Notes now)

**Comment by liamcain** [comment]
@hooksoft, hi, those shouldn't be necessary to set anymore. It was a bug that should be fixed now if update to the latest version (1.2.0) of the plugin.

You can upgrade from within the app if you go back to the plugin gallery.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/693981/98189852-d2530e00-1ee3-11eb-8327-f3e27f2221be.png">


**Note:** you might need to restart the app after you update, since the "update" button doesn't remove the older version properly yet.

Sorry about that hiccup, and let me know if you run into any other issues or have any suggestions!

**Comment by tedblizzard** [comment]
> Hi @tedblizzard, could you click on the "Console" in the devtools tab and send me a screenshot of that?
> 
> <img alt="image" width="292" src="https://user-images.githubusercontent.com/693981/98181628-b8103480-1ed1-11eb-9b1b-9e8856f61ee5.png">
> 
> Thanks!

Sorry still no calendar showing up.  What other information would be helpful?
![image](https://user-images.githubusercontent.com/2208182/98442626-3b32c400-2138-11eb-9d68-cd5a94984cd7.png)

**Comment by tedblizzard** [comment]
My fault.  It is working fine now.  Thank you.
