### ISSUE TITLE
Calendar doesn't display any daily note outside of the assigned folder.

### ISSUE THREAD

**Issue by timmyreal** [liamcain/obsidian-calendar-plugin#243]
### Describe the bug

After a small problem with the Obsidian Sync plugin, I noticed that none of my entries from before January 1, 2022 showed up on the calendar. When I navigated to an earlier daily note and used the Reveal Active Note command, the calendar will navigate to that date but there will be no dots for that date. If I click that date, it prompts me to create a completely new daily note for that date.
<img width="240" alt="Screen Shot 2022-04-13 at 1 18 09 PM" src="https://user-images.githubusercontent.com/82277734/163270008-d81a57e7-0864-4705-9888-d4ee4811392b.png">
<img width="239" alt="Screen Shot 2022-04-13 at 1 18 18 PM" src="https://user-images.githubusercontent.com/82277734/163270027-bec5b9c2-aa65-4a35-8cd2-d2a330e62f9b.png">

I disabled every snippet and plugin except for Calendar with no effect. I also uninstalled and reinstalled the calendar to no avail. No worthwhile information in the debug console.

The cutoff date seemed significant to me because all my daily notes are organized into different folders for each year (e.g. Journals 2019, Journals 2020, Journals 2021, etc.). All new notes are automatically filed into Journals 2022. To see if this was the problem, I moved some notes from 2021 into the 2022 folder and restarted Obsidian. Sure enough, they appear.
<img width="212" alt="Screen Shot 2022-04-13 at 3 51 45 PM" src="https://user-images.githubusercontent.com/82277734/163270074-396fb2f5-7524-42b7-a883-f6306b88c27f.png">

I moved the files back to the 2021 folder and restarted Obsidian again. The dots disappeared.
<img width="220" alt="Screen Shot 2022-04-13 at 3 53 08 PM" src="https://user-images.githubusercontent.com/82277734/163270217-26ed9663-0f01-4851-bb5b-76785ed6e42b.png">

The Calendar plugin has never had a problem displaying daily notes from different folders before. Maybe the new desktop update broke the calendar plugin.

### Steps to reproduce

1. Open calendar pane
2. Navigate to a month before 2022.
3. No entries appear.

### Expected behavior

The calendar will show all the daily entries from all previous years.

### Screenshots

See above.

### Environment (please specify)

Desktop

#### OS

macOS

#### Obsidian Version (e.g. v0.10.6)

v0.14.5

### Theme (if applicable):

ITS, but the bug appears in every other theme I've tried, including the default.

**Comment by timmyreal** [comment]
I kind of "solved" this by setting the default folder one level up so it catches all the entries in every folder inside. I'd prefer to have this year's folder be the default so I don't have to move them each time, but this will do for now.

**Comment by liamcain** [comment]
You can accomplish what you're after by changing the format. Set the format to `YYYY/YYYY-MM-DD` and it will create new entries in the correct sub-folder.
