### ISSUE TITLE
Calendar navigation doesn't adhere to pinned windows

### ISSUE THREAD

**Issue by lillianhorin** [liamcain/obsidian-calendar-plugin#25]
OS: Windows 10
Obsidian v.0.9.11

As usual, LOVING this plugin. Recently, I noticed that there has been a bug with regards to pinned windows. In Obsidian, typically if a window is pinned, if I try to open another window, it opens in a new pane. However this plugin seems to override that. If I pin a note and try to open a new daily note from the calendar plugin, it always opens on the pinned note instead of opening a new window. Note that this does not occur if I open a daily note from Obsidian's navigation.

Pinned window
![image](https://user-images.githubusercontent.com/24489520/98120630-304c0b00-1e7c-11eb-9122-7368307041fd.png)

Overridden pinned window after opening daily note from calendar plugin
![image](https://user-images.githubusercontent.com/24489520/98120709-4ce84300-1e7c-11eb-808f-5ea7d5360183.png)

**Comment by josecannete** [comment]
I'm experiencing the same on macOS Catalina & Obsidian 0.9.10.

Also, thank you so much for the plugin, is really useful!

**Comment by liamcain** [comment]
@lillianhorin Great catch! And thanks again for the detailed report. Will have a fix for this soon.

**Comment by liamcain** [comment]
This got added in version 1.2.0, after upgrading, you might need to restart Obsidian before the new behavior takes effect.
