### ISSUE TITLE
Calendar View does not open

### ISSUE THREAD

**Issue by OskarKrafft** [liamcain/obsidian-calendar-plugin#277]
> **Before Submitting:** Double-check that you are running the latest version of the plugin. The bug might have already been fixed 😄

### Describe the bug

After first installation, the calendar view does not appear on the sidebar and cannot be opened through the command palette.

I'm running on v1.0.3

Any help is appreciated

### Steps to reproduce

3. See error

### Expected behavior

_A clear and concise description of what you expected to happen_.

### Screenshots

![image](https://user-images.githubusercontent.com/112709389/199318009-cd0ca4eb-2990-4475-8000-f6329d96e6b9.png)

#### OS

[Windows]

#### Obsidian Version (e.g. v0.10.6)

v1.0.3

### Theme (if applicable):

Blue Topaz

**Comment by OskarKrafft** [comment]
can be closed. I just had to drag out the side pane and then the icon appeared...

**Comment by cvpeck** [comment]
Glad it's not just me then! Thanks for the fix.
