### ISSUE TITLE
Obsidian Calendar Theme

### ISSUE THREAD

**Issue by iepstein01** [liamcain/obsidian-calendar-plugin#28]
Hello,
    This isn't really an issue, but I was wondering what theme you used in the screenshot you have in README.md. It looks really good and I'd like to use it myself. 

Thanks!

**Comment by liamcain** [comment]
Hi, it's a combination of the [Minimal theme](https://github.com/kepano/obsidian-minimal) and [Nord](https://github.com/insanum/obsidian_nord).
