### ISSUE TITLE
Can't See Calendar View

### ISSUE THREAD

**Issue by Vuccappella** [liamcain/obsidian-calendar-plugin#306]
> **Before Submitting:** Double-check that you are running the latest version of the plugin. The bug might have already been fixed 😄

### Describe the bug

Can't see the calendar view.

![image](https://user-images.githubusercontent.com/5423643/222318085-6050b735-1246-411f-8cbc-b4df87b70abe.png)
Does not appear on the side bar at all.
![image](https://user-images.githubusercontent.com/5423643/222318459-268b41b9-fcdc-4b7e-a037-1b97ef1433e5.png)
Calendar: Open View command does not appear when going to command pallete.

Calendar: Open View command does appear in hotkey settings but when assigning a hotkey to it and pressing the hotkey nothing happens and I still can't see the Calendar View.

### Steps to reproduce

1. Install and enable plugin
2. Try and open the calendar view in any way

### Expected behavior

Calendar view should be visible on the right.
When running Open View command, calendar view should appear,
Calendar View Icon should be visible in sidebar at the top.
### Environment (please specify)
Windows 10 - Desktop

#### OS

Windows

#### Obsidian Version (e.g. v0.10.6)
Newest

### Theme (if applicable):
Default Theme

**Comment by adamjsturge** [comment]
@Vuccappella did you figure out how to fix this?

**Comment by nottrobin** [comment]
@Vuccappella I have this same problem - what was the solution for you?

**Comment by nottrobin** [comment]
Never mind, this was my issue https://github.com/liamcain/obsidian-calendar-plugin/issues/277#issuecomment-1299008889 :

> @OskarKrafft: can be closed. I just had to drag out the side pane and then the icon appeared...
