### ISSUE TITLE
Nothing happens when "Calendar: Open View" is run

### ISSUE THREAD

**Issue by LiamHz** [liamcain/obsidian-calendar-plugin#32]
When I run "Calendar: Open View" through the command palette or via hotkeys, nothing happens.

**Comment by liamcain** [comment]
Hi @LiamHz, I should probably clarify it in the docs, but `Open View` is intended to re-open the calendar view if you close it for any reason

e.g. 
<img width="340" alt="image" src="https://user-images.githubusercontent.com/693981/98605728-ecaa3480-22b3-11eb-8a9e-c57a4139e17c.png">

However, the calendar intentionally doesn't open another copy of the view if you have one open already.

Could you clarify what behavior you were expecting? Are you interested in having multiple calendar views open at once?

**Comment by LiamHz** [comment]
Ahh, I didn't know that the Calendar could be closed.

I was expecting that it would open the right-hand pane, and open the calendar tab

**Comment by liamcain** [comment]
In v1.2.1, the "Calendar: Open View" command won't show in the command palette unless the view is closed. This should clear up confusion. 

Feel free to create a separate issue if you think a command for (toggling the sidebar and) focusing the calendar view would a good addition!
