### ISSUE TITLE
Unable to Create File

### ISSUE THREAD

**Issue by OogieM** [liamcain/obsidian-calendar-plugin#336]
> **Before Submitting:** Double-check that you are running the latest version of the plugin. The bug might have already been fixed 😄

### Describe the bug

New since installing version 1.4.16 of Obsidian I can no longer click on the calendar to create a daily note. I get an "Unable to create new file." error. But I can create a new note in the vault using the normal Obsidian create note options. 

### Steps to reproduce

1. Go to the calendar view.
2. Click on any date for which a new note does not exist.
3. See error "Unable to create new file" and the note is not created. 

### Expected behavior

New note created using my template as it was done for the previous year+.

### Screenshots

_If applicable, add screenshots to help explain your problem._

#### OS

Macintosh Ventura 13.6

#### Obsidian Version (e.g. v0.10.6)

1.4.16

### Theme (if applicable):

_If the bug is visual, please provide the name of the Community Theme you're using._

**Comment by ciceroxiao** [comment]
Do not use "yyyyMMDD" for the date format of the "Diary" plugin.

**Comment by OogieM** [comment]
I don't use the diary plugin. 

But I should have come back and indicated that after a while there was a new version of Obsidian out with a new Installer and after doing that re-install the bug is gone and I do get my proper template and file created.

**Comment by ciceroxiao** [comment]
The "Diary" plugin is the core plugin that comes with Obsidian. I had the same problem as you, then I changed the date format of the "Diary" plugin, and the problem didn't occur anymore. Sorry, I'm a Chinese user and I use Chinese.
![image](https://github.com/liamcain/obsidian-calendar-plugin/assets/115197878/1f4d77ea-48b0-4e7d-82ac-2c43c3857611)

**Comment by OogieM** [comment]
Ah, on my system it's called daily notes and I never had that as my date format anyway. Mine looks like this 
<img width="1066" alt="Screenshot 2024-02-18 at 4 01 40 PM" src="https://github.com/liamcain/obsidian-calendar-plugin/assets/2394446/d8df30d6-7740-4497-aa09-c1953c68d593">

**Comment by ciceroxiao** [comment]
> I don't use the diary plugin.
> 
> But I should have come back and indicated that after a while there was a new version of Obsidian out with a new Installer and after doing that re-install the bug is gone and I do get my proper template and file created.

Uh-huh. I mean, you could try changing your date format until the plugin can create or recognize the journal file properly. The reason? I checked the history of issue submissions and realized that the developer has not responded to this issue - which implies that, in the short term, the developer won't be able to resolve this issue for you.

**Comment by OogieM** [comment]
The developer doesn't have to respond. The issue is gone, done fixed. My solution was described in the message you responded to. If youa re still having problems with the date formats then I suggest you re-install Obsidian using a new Installer version like I did and see if that fixes it for you.
