### ISSUE TITLE
Add a monthly note

### ISSUE THREAD

**Issue by mamoit** [liamcain/obsidian-calendar-plugin#36]
I find extremely useful to have a monthly note where I keep my TODOs for example.
A little bit in the bullet journal philosophy.

We could click on the month in the calendar to go to it.
Or `ctrl+p` "Open this month's note" or "Open monthly note".
This would probably require another configuration for the monthly naming schema.

This also opens the question if an yearly note makes sense, and to be honest, I have not yet felt the need for it.

**Comment by liamcain** [comment]
@mamoit Oh, interesting. Do you also use weekly notes? Or just monthly? I will be adding weekly notes soon and the functionality is similar, but I also want to avoid cluttering the UI too much.

Currently, clicking on the month in the calendar will take you back to the current month in the calendar view. So it might need a different home. 

Thanks for the request!

**Comment by mamoit** [comment]
Humm... I don't use weekly notes no :thinking: maybe it's not a bad idea, the months can become a little bit cluttered, and in the weekend I can always find time to migrate TODOs to the next week.

The only problem I can see that we may run into is naming.

For the month it's just `202011.md` and you keep it sorted with the daily ones.
For the weekly, maybe something like `20201116W47.md` where the `W%d%d` is the week number of the year and the YYYYMMDD is the day of Sunday/Monday?
Maybe even leave the start of the week configurable based on the start of the week setting?
This way you can keep order.

Regarding the "where to click to get a monthly/weekly note" situation, with 5min of thinking (read: not the most thought through idea ever), I'd say that the `today` button could get it's own place.
I didn't know about the "click on the month to go to today" functionality, so the UI is not that intuitive as it is (at least in my experience).

For the weekly note, maybe add the week days in smaller font to the left of each week, and there it's easy to see them and keep them intuitive.
The week numbers should be toggleable though, since i guess a lot of people don't like them that much.

**Comment by liamcain** [comment]
Week numbers will be toggleable, and clicking on them will generate `YYYY-[W]ww.md` by default. Here's a sneak peak of the calendar with them: 

<img width="383" alt="image" src="https://user-images.githubusercontent.com/693981/99564946-112f9c00-2999-11eb-8122-4650fcf9a00b.png">

> I didn't know about the "click on the month to go to today" functionality, so the UI is not that intuitive as it is (at least in my experience).

That experience is borrowed from [Fantastical](https://flexibits.com/fantastical), but I'm not opposed to having it as a separate button similar to Google Calendar.

I'll still need to give the monthly/yearly notes more thought but I appreciate all the input!

**Comment by liamcain** [comment]
@mamoit I integrated some of your suggestions into the latest version (1.3.0). Sadly monthly notes didn't make the cut, still need to give it a bit more thought.

**Comment by mamoit** [comment]
Wow, you're fast!
And such extensive doc too! Looking goooood :1st_place_medal:

> That experience is borrowed from Fantastical

Didn't know that, and it makes sense to keep being consistent with the "industry standard" unless there's a good reason to deviate.

> Sadly monthly notes didn't make the cut, still need to give it a bit more thought.

I already started using the weekly notes as soon as you suggested :smile:
And come on, it was just an idea.
1. it doesn't need to be implemented
2. it will require time to think it through and pull it off.

1 small improvement that I can point out right now.
`settings > calendar` and then both on the template and the folder, they could list the available ones, like what you have on the daily note's `new file location` and `template file location`.

I have another one but that deserves a separate issue :)

**Comment by mamoit** [comment]
Mmmm, there seem to be no indicator dots for the week, this would very useful (especially the incomplete TODO ones).

**Comment by mamoit** [comment]
I have "week starts on Monday" set, and created a template for the overview more or less as you suggested in the README:
```
## Week at a Glance

![[{{monday:YYYYMMDD}}]]
![[{{tuesday:YYYYMMDD}}]]
![[{{wednesday:YYYYMMDD}}]]
![[{{thursday:YYYYMMDD}}]]
![[{{friday:YYYYMMDD}}]]
![[{{saturday:YYYYMMDD}}]]
![[{{sunday:YYYYMMDD}}]]
```
and it gets rendered to
```
## Week at a Glance

![[20201116]]
![[20201117]]
![[20201118]]
![[20201119]]
![[20201120]]
![[20201121]]
![[20201115]]
```
It seems that the `sunday`does not take the "week starts on Monday" into account.
Or maybe there is some kind of convention that I'm not aware of, since week numbers may be offset by 1 if a 1st of January falls on a Sunday or Monday.

**Comment by liamcain** [comment]
> Mmmm, there seem to be no indicator dots for the week, this would very useful (especially the incomplete TODO ones).
This makes me think how would you represent them for the month 🤔 not easy indeed.

Yea I've gone back and forth over adding the dots to the weekly notes (don't want it to get too cluttered). I agree it's not the best UX currently though. I'm going to start using weekly notes more so I get a feel for what's best in this case. But always open to ideas!

> It seems that the sundaydoes not take the "week starts on Monday" into account.

Oh interesting. I could have sworn I tested this. Good catch! I'll need to localize the date properly for the weekly template.

**Comment by mamoit** [comment]
According to [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601#Week_dates) you got the calculation of the week wrong.

This year is not affected, but the last week of 2021 is supposed to be 53, not 52.
The (ISO) rule seems to be:
> if 1 January is on a Monday, Tuesday, Wednesday or Thursday, it is in week 01. If 1 January is on a Friday, Saturday or Sunday, it is in week 52 or 53 of the previous year (there is no week 00). 28 December is always in the last week of its year.

**Comment by liamcain** [comment]
I'm using the locale week number, not the ISO week number. That seems to be the more common standard (Apple Calendar, Fantastical, Google Calendar all follow this convention).

**Comment by mamoit** [comment]
Mm... I switched my locale (had it in us -.-') to Portuguese.
The last week of the year is still 52, I thought it was because I was running Obsidian's flatpak version, but no, the AppImage one still says 52.
Opened the native calendar app (Korganize) and it shows that the last week is 53.
Is the locale checked every time, or is it kept in a config somewhere?

**Comment by liamcain** [comment]
Unfortunately, Obsidian doesn't expose locale information yet. So `moment.locale()` won't do anything. Is there any reason you don't want to follow the 52 week approach?

**Comment by mamoit** [comment]
Because I don't live in America, so I use ISO :smile:
Now for real, I'm being picky just to try to make it perfect, I'll survive with this "issue".
But maybe Obsidian could expose the locale :thinking:

**Comment by mamoit** [comment]
From the info provided from the issue in the obsidian-api repo, I think you can do something like:
```
moment.locale(app.getLocale());
```
my js/ts skills are non existent though, I'm just speculating.

**Comment by Warden20** [comment]
The Monthly note would be the last piece to make this plugin awesome.

**Comment by flyaway1217** [comment]
I plan to use this plugin as my diary system. It would nice to have monthly and yearly notes.

**Comment by liamcain** [comment]
#### Update on the plan here:

I'm going to split "Weekly Notes" into its own separate plugin (it will still integrate with the calendar). This will open up introducing Monthly and Yearly notes (TBD if those should all fit into a single separate plugin or multiple).

This should also help with a few other things:
- simplifying the Calendar core
- set a precedent for how other plugins can interface with the calendar
- Allow people to mix and match workflows without being overwhelmed with configuration

**Comment by mamoit** [comment]
Is plugin dependency supported by Obsidian?
Such that the others can install core automatically.

**Comment by liamcain** [comment]
Monthly Notes are now available through the [Periodic Notes](https://github.com/liamcain/obsidian-periodic-notes) plugin. I haven't added a calendar integration yet though since I still need to find a place to fit it in the UI 😅
