### ISSUE TITLE
Ignore hour\minute\second timestamp in note

### ISSUE THREAD

**Issue by ze-kel** [liamcain/obsidian-calendar-plugin#40]
If you have "YYYY-MM-DD HH-mm" in you note the plugin won't work for yesterday note because it's looking for one with yesterday date and current time.

**Comment by liamcain** [comment]
Hi, thanks filing! Just to check: you still only have 1 note per day, but it includes the timestamp, is that right?

I tried it out and that seems to be the behavior of the daily note plugin so it makes sense to mimic.

**Comment by ze-kel** [comment]
Yes. For example I have a note from september 22 named as "2020.09.22 11-13". But it doesn't show up. If I manually click on sept 22 in calendar I get "File 2020.09.22 15-42 does not exist. Would you like to create it?" 15-42 is current time at the moment of clicking.

**Comment by liamcain** [comment]
@ze-kel This should now work as expected in v1.4.0. Let me know if there are still any issues!
