### ISSUE TITLE
Right click on a date/week to access the note's context menu

### ISSUE THREAD

**Issue by mamoit** [liamcain/obsidian-calendar-plugin#41]
Maybe right clicking on a day/week could behave the same as right clicking in the note on the file tree, and have at least the following options:
* delete
* copy obsidian url
* show in system explorer

and maybe "make a copy" too? the "rename" does not make that much sense to be honest.

What drove this feature request is that I have found myself clicking on a day, creating a note by mistake and then trying to right click it to delete it.

**Comment by liamcain** [comment]
> What drove this feature request is that I have found myself clicking on a day, creating a note by mistake and then trying to right click it to delete it.

You could enable "Confirm before creating new note" to avoid this.

But having a context menu still makes sense to me! Especially if you're using it as an alternative navigation to the file explorer.

**Comment by mamoit** [comment]
> You could enable "Confirm before creating new note" to avoid this.

Aaand, done! :+1:

**Comment by liamcain** [comment]
This was added in v1.4.13

**Comment by mamoit** [comment]
Works perfectly :+1:
