### ISSUE TITLE
Incomplete TODO indicator does not handle * [ ]

### ISSUE THREAD

**Issue by mamoit** [liamcain/obsidian-calendar-plugin#42]
I was trying to figure out why my TODOs were not showing up as incomplete in the calendar.
Apparently, obsidian prefers the notation `- [ ]`, but it also formats `* [ ]`, which I was using.
As soon as I switched, it worked.
Should you support the Obsidian supported, but apparently non standard notation too?

**Comment by liamcain** [comment]
Oh, interesting. I didn't realize that was supported. Will add to the next version! Good catch.

**Comment by liamcain** [comment]
Added in #55
