### ISSUE TITLE
Theme about OB

### ISSUE THREAD

**Issue by wongFanx** [liamcain/obsidian-calendar-plugin#46]
I'm terribly sorry, but I have an unrelated question.  
I really like your OB theme. Can you share it?  Thank you!

![image](https://user-images.githubusercontent.com/14831158/99834420-596bdb80-2b9e-11eb-81c8-58ae10ec6812.png)

**Comment by wongFanx** [comment]
It's really beautiful. It's perfect for my taste.😝

**Comment by liamcain** [comment]
It's the "[Minimal](https://github.com/kepano/obsidian-minimal)" theme but I tweaked the colors to match the [Nord](https://www.nordtheme.com/) color scheme

**Comment by wongFanx** [comment]
Thank you very much!  I've tried to modify some CSS.  
But I can't find out where to change the color of the text of the article. Can you tell me?  Thank you.

**Comment by wongFanx** [comment]
I've tried to modify some CSS.  
But I can't find out where to change the color of the text of the article. Can you tell me?  Thank you.

**Comment by wongFanx** [comment]
![image](https://user-images.githubusercontent.com/14831158/99886957-70ccc680-2c7b-11eb-91e2-62599fe5ab88.png)
I'm trying to add color here, but it seems to control only the text Color in "markdown mode."  Instead of text in PREVIEW MODE

**Comment by wongFanx** [comment]
There is a strange problem, "markdow mode" and "browse mode", the line height is the same, but the line wrap height is different.
![image](https://user-images.githubusercontent.com/14831158/99888414-9bbd1780-2c87-11eb-8020-f23060207c2b.png)

**Comment by wongFanx** [comment]
How to modify this? Thanks!

**Comment by liamcain** [comment]
Hi @wongFanx, if you think it's an issue with the theme, I recommend raising this issue on the theme's github page. From your screenshot it looks like there is an empty line between the paragraphs on the left. When you render Markdown, it will ignore single newlines between paragraphs.

There is an option in the settings to change that behavior. Maybe flipping this switch in `Settings > Editor` will help.
<img width="923" alt="image" src="https://user-images.githubusercontent.com/693981/99889024-70064700-2c1f-11eb-9537-f8e82ef4d327.png">
