### ISSUE TITLE
CSS For Weekends

### ISSUE THREAD

**Issue by TechPlasma** [liamcain/obsidian-calendar-plugin#48]
I like to have the weekend columns a different color on my Calendar so it's easier to know which days are the weekend. This is helpful since I use Monday as the first day of the week, but am conditioned to think of Sunday as the first. 

I'd be fine with the dates themselves a different color, though I'd prefer to have the entire column a different color.

**Comment by liamcain** [comment]
Good call. I'll add this for the next version!

**Comment by liamcain** [comment]
As of v1.4.0, there is now a `var(--color-background-weekend)` css variable.
