### ISSUE TITLE
Enhancement: Enable the calendar to resize automatically to fit horizontal container

### ISSUE THREAD

**Issue by pauljacobson** [liamcain/obsidian-calendar-plugin#49]
I've recently started using the Calendar plugin, and it's awesome! One thing I'd love to see is the option to automatically resize the width of the calendar to fit the container.

![20201126_075709_screenshot](https://user-images.githubusercontent.com/2912202/100313850-1b1b5580-2fbe-11eb-80fb-d93a6e915656.gif)

### Steps to reproduce

1. Enable the Calendar plugin in the Obsidian sidebar
2. The calendar has a fixed width in wider sidebars
3. Resizing the sidebar doesn't resize the calendar unless the sidebar is resized to be as narrow as the calendar

### What I'd like to see

I'd like to see the calendar resize horizontally to fit the container, here:

![Markup on 2020-11-26 at 08:02:57](https://user-images.githubusercontent.com/2912202/100313710-d8f21400-2fbd-11eb-96a8-2e55373d3f8d.png)

### What happened instead

As I mentioned above, the calendar has a fixed, maximum width, so it doesn't look as good as it would if it resized automatically.

#### App / plugin / OS version

Obsidian: v0.9.16 and v0.9.17
Calendar: v1.3.1
OS: macOS 11.0.1

**Comment by liamcain** [comment]
@pauljacobson Hi Paul, this behavior appears to be an issue with your custom theme/CSS. If you disable custom CSS in your settings, the default behavior should be that the calendar scales with the container. I recommend bringing this issue up with the theme creator.

<img width="882" alt="image" src="https://user-images.githubusercontent.com/693981/100352502-12755000-2fbb-11eb-88ca-04b7d3d3dbde.png">


Here's the "vanilla" UI for reference:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/693981/100352667-55372800-2fbb-11eb-981c-16a8aba4292d.png">

**Comment by pauljacobson** [comment]
> Hi Paul, this behavior appears to be an issue with your custom theme/CSS. If you disable custom CSS in your settings, the default behavior should be that the calendar scales with the container. I recommend bringing this issue up with the theme creator.

Ah, thank you for pointing that out. I'll see if I can track down the classes for this, and perhaps work around that in the meantime. I don't suppose you could point me in the right direction?

**Comment by pauljacobson** [comment]
Also, @liamcain Are you testing with v0.9.18 with the CSS snippets feature? Just noticed the screenshot text.

**Comment by liamcain** [comment]
> I don't suppose you could point me in the right direction?

What's the name of the theme you're using? You'll likely just need something like:

```css
#calendar-container table {
  width: 100%;
}
```

But I can't tell for sure without knowing the theme.

> Are you testing with v0.9.18 with the CSS snippets feature?

I haven't tried out the CSS snippets quite yet, but good eye! 👀

**Comment by pauljacobson** [comment]
> What's the name of the theme you're using?

It looks like I'm using the [Comfort color dark](https://github.com/obsidian-ezs/obsidian-comfort-color-dark) theme here. I'll poke around at the Custom CSS, and see if I can resolve this issue.

**Comment by pauljacobson** [comment]
I did a couple tests with other themes, and it looks like this is a theme issue. It seems to affect a related theme, Comfort Smooth, that looks like a derivative of the Comfort color dark theme.

**Comment by liamcain** [comment]
oh, I see. Looks like the theme sets `display: block` on the `.table` class and that's affecting the calendar. Since that's the case, I think I'll rename the class on my end to avoid the collision.

If you want a temporary fix, you should be able to add the following to your obsidian.css:

```css
#calendar-container .table {
  display: table;
} 
```

**Comment by pauljacobson** [comment]
Perfect, that works. Thank you.

**Comment by liamcain** [comment]
As of v.1.4.0, I renamed the CSS class to `.calendar` (it was `.table`). This should fix the styling collision.
