### ISSUE TITLE
Wrong position for Sunday in template (when  start week from Monday)

### ISSUE THREAD

**Issue by bigv027** [liamcain/obsidian-calendar-plugin#51]
I love this update version（1.3.1）very much, it helps me a lot on weekly note, thanks for your great job！
Would you pls check the pic, I'm used to starting the week from Mon, but when I use following template, the Sunday seems still be last week of Sunday. Could you kindly fix it?  

```
# {{title}}

## 🌟🌟🌟
- [ ] 
- [ ] 
- [ ] 

## {{monday:YYYY-MM-DD [Mon]}}
- [ ]  

## {{tuesday:YYYY-MM-DD [Tue]}}
- [ ]  

## {{wednesday:YYYY-MM-DD [Wed]}}
- [ ]  

## {{thursday:YYYY-MM-DD [Thu]}}
- [ ]  

## {{friday:YYYY-MM-DD [Fri]}}
- [ ]  

## {{saturday:YYYY-MM-DD [Sat]}}
- [ ]      

## {{sunday:YYYY-MM-DD [Sun]}}

```
<img width="1089" alt="WX20201127-170120@2x" src="https://user-images.githubusercontent.com/16148316/100430937-6a52aa80-30d2-11eb-8bde-e92ba047974d.png">

**Comment by liamcain** [comment]
Hi @bigv027, thanks for the report. This will get fixed for the next version.

**Comment by liamcain** [comment]
Add this in #55
