### ISSUE TITLE
Weekly note file name syntax

### ISSUE THREAD

**Issue by DutchPete** [liamcain/obsidian-calendar-plugin#52]
Hi, I have had my file name syntax for years: `Week-YYYY-ww`. The Calendar plug-in translates the word Week into a number. What should I put to get the word "Week" (w/o the quotation marks).

**Comment by liamcain** [comment]
Hi @DutchPete, you can put "unformatted" words in the note name but surrounding them with `[]` brackets. So your example would be `[Week]-YYYY-ww`.

**Comment by DutchPete** [comment]
Thanks Liam, that works fine.

**Comment by liamcain** [comment]
(Add more info about this in the README)
