### ISSUE TITLE
Show days for next/previous months in the calendar's blank space

### ISSUE THREAD

**Issue by jacklaing** [liamcain/obsidian-calendar-plugin#54]
If I'm at the beginning/end of a month, it's inconvenient to have to click the arrows to navigate between months to look at yesterday/tomorrow's daily note. The days for the end/beginning of the neighboring months should be visible in the calendar widget (greyed out) and clickable.

Here's an example
![image](https://user-images.githubusercontent.com/43007530/100553690-1b9a4180-3287-11eb-959a-afef7fb2462c.png)

**Comment by liamcain** [comment]
I added this in #55
