### ISSUE TITLE
Add jump to today

### ISSUE THREAD

**Issue by adxsoft** [liamcain/obsidian-calendar-plugin#56]
Excellent plugin. Use it every day.
Would be useful if clicking on TODAY at top right between < and > buttons jumps to today and highlights it. Currently it down not respond to a mouse click. I'm using Mac OSX and Obsidian 9.17

**Comment by liamcain** [comment]
Hi @adxsoft! This should already be the current behavior of the "Today" button. If you are looking at April, for example, clicking "Today" should return you to November. Likewise the cell for today should already be styled differently:

<img width="424" alt="image" src="https://user-images.githubusercontent.com/693981/100688901-5ff21400-3351-11eb-8ff8-6505c16f9f6a.png">

^ Styling might very based on the theme you are using (some themes try to make this a lot more subtle).

Let me know if that's different from the behavior you're experiencing.

**Comment by adxsoft** [comment]
Hi Liam

I misunderstood the behaviour. I thought it would make today the selected day and select it (as shown on 22nd Nov in your attachment).

Cheers
Allan @ adxsoft

**Comment by liamcain** [comment]
I see! This was why I was hesitant to use the word "Today" for the button, but that seems to be standard practice among  popular Calendar apps (e.g. Apple Calendar, Google Calendar).

For the behavior you're interested in, you already have a few options from the daily notes plugin:
- Command Palette (`Open today's note`)
- Clicking `Open today's note` from the left sidebar
- Binding it to a hotkey.

Let me know if you have any other ideas/suggestions though, especially ways to make this more clear!

**Comment by adxsoft** [comment]
I agree that behaving like Apple and Google calendars is important. I'll be
using the left sidebar option to open todays note from  now on.

Thanks for explaining the design approach and well done on a very useful
plugin.

Cheers
Allan @ adxsoft


On Dec 1, 2020 at 23:38, Liam Cain <notifications@github.com> wrote:

I see! This was why I was hesitant to use the word "Today" for the button,
but that seems to be standard practice among popular Calendar apps (e.g.
Apple Calendar, Google Calendar).

For the behavior you're interested in, you already have a few options from
the daily notes plugin:

   - Command Palette (Open today's note)
   - Clicking Open today's note from the left sidebar
   - Binding it to a hotkey.

Let me know if you have any other ideas/suggestions though, especially ways
to make this more clear!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/liamcain/obsidian-calendar-plugin/issues/56#issuecomment-736525739>,
or unsubscribe
