### ISSUE TITLE
Send item/block from one daily/weekly note to another

### ISSUE THREAD

**Issue by wenlzhang** [liamcain/obsidian-calendar-plugin#59]
One may arrange things/actions in daily/week notes. Sometimes one may need to move an item/block within a daily/week note to another daily/weekly note. Therefore, it would be great if this plugin is able to move/send a certain item/block/part of a daily/week note to another daily/weekly note. This may be achieved through the following steps:

1. Select an item/block of a daily/weekly note in a daily/weekly note
2. Press hotkey to select the destination daily/weekly note
3. Automatically send the item/block to the beginning/end (maybe this can be option in the plugin) of the desired daily/weekly note

**Comment by liamcain** [comment]
This is a cool idea (and would feel functionally similar to how it's handled in Things.app, which I love). I think it deserves its own plugin though!

---

It's functionally similar (but not quite the same as) the [Review plugin](https://github.com/ryanjamurphy/review-obsidian) by @ryanjamurphy. Maybe another collab opportunity?

**Comment by ryanjamurphy** [comment]
> It's functionally similar (but not quite the same as) the Review plugin by @ryanjamurphy. Maybe another collab opportunity?

For sure. In fact, [I think it's already been requested for Review](https://github.com/ryanjamurphy/review-obsidian/issues/12). (Actually, it's already possible to link/embed blocks into daily notes with natural language in Review, but the UX can be improved as @jacklaing suggests in that linked issue.)

**Comment by wenlzhang** [comment]
Just tried the Review plugin, it's really cool. It would be really great if the functionality of Review and Calendar can be integrated in some way. The following issue may also be related:
https://github.com/lynchjames/obsidian-day-planner/issues/10

It might also be interesting to somehow combine the features of the following plugins:

- The Workbench plugin by @ryanjamurphy
  - This can be used for writing/improving temporary/inbox notes.
- The Review plugin for GTD weekly review
- The Calendar plugin for managing GTD calendar events
- The Todoist Sync Plugin for syncing tasks from Obsidian to Todoist
  - This is discussed here: https://github.com/jamiebrynes7/obsidian-todoist-plugin/issues/43
  - The synced tasks in Todoist can also be two-way synced to Google Calendar.

Maybe it is a little off the topic, but it would also be interesting to be able to move/send item/block of any note to another note.

**Comment by tgrosinger** [comment]
@wenlzhang check out the [refactor plugin](https://github.com/lynchjames/note-refactor-obsidian) for moving blocks to a new note. I don't think it supports moving into an existing note yet, but that might be a good feature request.

**Comment by wenlzhang** [comment]
@tgrosinger Thanks for suggesting this awesome plugin. Will try that later.

**Comment by liamcain** [comment]
This feature now exists in [Slated](https://github.com/tgrosinger/slated-obsidian/), which is powered by the same calendar core as this plugin. So go check it out!
