### ISSUE TITLE
Unable to auto-create weekly notes from previous months

### ISSUE THREAD

**Issue by bk7312** [liamcain/obsidian-calendar-plugin#62]
I've started using weekly notes and noticed a few minor bugs. 

When I change the calendar to Oct or Nov or some previous month, clicking on the weeks does not create a weekly note for that week. So if I click on week 42 in Oct, it says 2020-W50 doesn't exist and asks whether I want to create it.

Another bug is when I click week 51 and it says week 50 doesn't exist and ask if I want to create it. This might be related to the Sunday/Monday start or the ISO/Locale week counting system. I'm using Monday start on ISO and used 2020-[W]WW on the weekly note format. Might that be the reason? Edit: Never mind, I think you answered this from the week 53/1 error thread :D

**Comment by liamcain** [comment]
Great catch! Will make a fix for that soon~

**Comment by liamcain** [comment]
This should be fixed in 1.4.3
