### ISSUE TITLE
Different CSS class name

### ISSUE THREAD

**Issue by dxcore35** [liamcain/obsidian-calendar-plugin#8]
For some reason the CSS class name of the plugin is:

`#calendar-container.svelte-wd85n9.svelte-wd85n9`  not `#calendar-container`

**Comment by dxcore35** [comment]
But only the class name `#calendar-container .svelte-wd85n9.svelte-wd85n9` with the space between works.

**Comment by liamcain** [comment]
`#calendar-container` is any Id, not a CSS class. I updated the documentation to clarify that you should use `!important` for the time being. This will change in the next release though.
