### ISSUE TITLE
Support of Nested Folders for weekly notes

### ISSUE THREAD

**Issue by Warden20** [liamcain/obsidian-calendar-plugin#82]
The support of nested folders for daily notes is awesome, but it doesn't work for the weekly notes. Is it possible to make it work for weekly notes?

**Comment by liamcain** [comment]
Hi, @Warden20. It's not possible yet, but this is planned!

**Comment by liamcain** [comment]
This was added in v1.5.0. Let me know if there are any issues!

I also released a new plugin called [Periodic Notes](https://github.com/liamcain/obsidian-periodic-notes) which will be the home for Weekly Notes (as well as daily and monthly notes) going forward. Once you install it, your settings will be migrated over and everything should Just Work ™️.
