### ISSUE TITLE
Stopped Special Show of ”BREAK” Times

### ISSUE THREAD

**Issue by lwb52** [liamcain/obsidian-calendar-plugin#84]
A few days ago the plugin stopped moving BREAK items to the bottom of the Gantt chart, as shown in the edit-view below:

BREAK     :23-00, 0mm
section Breaks
And it was not possible to directly edit the Mermaid chart during that same day, while it was ”live”—the chart-edit would revert (”un-edit”) at the next auto-update…

**Comment by liamcain** [comment]
Hi @lwb52, this issue looks like it was intended for the [day-planner](https://github.com/lynchjames/obsidian-day-planner/issues) plugin instead of the Calendar!
