### ISSUE TITLE
First week of year creates weekly note for previous year

### ISSUE THREAD

**Issue by Juice805** [liamcain/obsidian-calendar-plugin#86]
The extension reads 2020-W1 as the last week of 2020/first week of 2021. When it should show as last week 2019/first week of 2020.
<img width="169" alt="Screen Shot 2020-12-23 at 2 37 15 PM" src="https://user-images.githubusercontent.com/8647159/103041832-6a589580-452c-11eb-8fba-c19293a5ed35.png">
<img width="326" alt="Screen Shot 2020-12-23 at 2 36 47 PM" src="https://user-images.githubusercontent.com/8647159/103041827-675da500-452c-11eb-9510-9964d7c17793.png"> <img width="315" alt="Screen Shot 2020-12-23 at 2 37 11 PM" src="https://user-images.githubusercontent.com/8647159/103041831-688ed200-452c-11eb-846e-fc6b609905aa.png">

**Comment by liamcain** [comment]
Oh, wow, great catch! Will make a hotfix for this.

**Comment by liamcain** [comment]
Fixed this in v1.4.8!

**Comment by rainydevbs** [comment]
Using Calendar version 1.4.19, this seems to have popped up again

I'm sing the weekly note's format `gggg-MM-DD [Week] ww`

![image](https://user-images.githubusercontent.com/10121527/106344329-911a9200-6277-11eb-87a1-32e142b00d6e.png)
First week of January 2021 shows this:
![image](https://user-images.githubusercontent.com/10121527/106344341-95df4600-6277-11eb-8fa5-2ff2a4cc3bc7.png)

![image](https://user-images.githubusercontent.com/10121527/106344412-ca530200-6277-11eb-94c7-305b1ce90a5c.png)
![image](https://user-images.githubusercontent.com/10121527/106344431-e2c31c80-6277-11eb-8fda-887f864e9c4b.png)
