### ISSUE TITLE
Change of the background

### ISSUE THREAD

**Issue by dxcore35** [liamcain/obsidian-calendar-plugin#9]
![Screenshot 2020-10-30 at 11 58 15](https://user-images.githubusercontent.com/7279156/97663195-51d97b00-1aa7-11eb-90ab-86ae2205e5f3.jpg)

I cannot find classes where I can change the background of remaining days to transparent.
Im talking about days...
1,2,3...
13,14,15...and so on

**Comment by liamcain** [comment]
I updated the available CSS variables that you can override in v1.1.0. You can see the full list here: https://github.com/liamcain/obsidian-calendar-plugin#customization
