### ISSUE TITLE
Incorrectly named weekly note

### ISSUE THREAD

**Issue by tgrosinger** [liamcain/obsidian-calendar-plugin#91]
Just noticed an minor edge case when creating a weekly note that crosses years. Notice how the note is named `2020-W01` but should be `2021-W01`.

![image](https://user-images.githubusercontent.com/597386/103182341-8b3c2600-485f-11eb-9933-7463dab1d3ba.png)

**Comment by liamcain** [comment]
This should have been fixed in v1.4.8 (duplicate of #86), make sure you're running the latest version

**Comment by tgrosinger** [comment]
Yes, it is working after an upgrade. Thanks!
