### ISSUE TITLE
week 53/2020 vs 1/2021

### ISSUE THREAD

**Issue by DutchPete** [liamcain/obsidian-calendar-plugin#93]
I saw your comment about the update, but am not sure how to implement it. I updated the plug-in.

My settings are as follows:
![image](https://user-images.githubusercontent.com/10794265/103262449-a4eb8380-49ad-11eb-8449-4e6db5a331a6.png)

Yesterday I let the plug-in create a new note for this week, which is 1/2021. I want it to be 53/2020. Is there anything I can do?

**Comment by liamcain** [comment]
There's currently no way to switch to using the ISO week numbering system right now. The closest option would be to switch the locale that the Calendar is using:

<img width="858" alt="image" src="https://user-images.githubusercontent.com/693981/103289619-a325be00-49b5-11eb-9a55-048225422fec.png">

If you change this setting to `en-GB` (or another locale that's more appropriate), you'll see 53 weeks. Note: this will change the locale globally, so it might update the "Week Starts On" day as well.

**Comment by DutchPete** [comment]
Thanks, that works. However ………… the theme I was using got thrown out with the update, and now, when I want to install it via community themes it does not do it. Even if I put the theme's CSS sheet in the `.obsidian/themes` folder manually, Obsidian does not 'see" it. This has not happened with the vaults where I don't have the calendar plug-in installed.

**Comment by liamcain** [comment]
@DutchPete You mean the whole theme isn't applied? Or the theme isn't styling the calendar correctly? If it's the latter, could you direct me to the theme? I've noticed some community themes don't do a good job targeting the calendar with CSS (meaning they break on subsequent versions). If you can direct me to the theme repo, I can help the author update it.

**Comment by DutchPete** [comment]
I don't know what happened, but after updating to 0.10.3 everything is back to normal. A quirk at my end. Thank you for your help.
