### ISSUE TITLE
Weekly notes : keyboard shortcut fails to open weekly if it already exists

### ISSUE THREAD

**Issue by Mpic** [liamcain/obsidian-calendar-plugin#94]
When I hit the keyboard shortcut to open the current, existing weekly note (correctly named), it prompts to create it and fails if I ask it to.  
If the weekly note doesn't exist, it correctly creates it without any problem.

I'm on `fr` locale, weekly note format `gggg-[W]WW` if that is relevant.

**Comment by liamcain** [comment]
Can reproduce, will make a fix shortly.

**Comment by liamcain** [comment]
This should now be fixed in v1.4.11. Sorry about that!
