### ISSUE TITLE
Idea: Colorisation of days depending on note content

### ISSUE THREAD

**Issue by adxsoft** [liamcain/obsidian-calendar-plugin#96]
**New Feature/Idea - Additional Settings Option**

_If the Daily Note contains string X then color the day number Y_

```
X could be *any* string

   '- [ ] ' for open tasks
   '#open' for tag open
   '#urgent' for tag urgent
   etc.

Y is the color for the day number
```
My use case is I would like the days that contain open tasks to show the day no in red so that I can check them and move them forward in the calendar and they do not get overlooked.

Just an idea but would be pretty cool feature

**Happy New Year!**
Allan @ adxsoft

**Comment by liamcain** [comment]
Hi Allan,

This is actually currently possible if you're comfortable with [frontmatter](https://publish.obsidian.md/help/Advanced+topics/YAML+front+matter). I'm considering this a beta feature for now; in the future, I will likely add support for tags anywhere in the file as well.

But here is the guide for how to use the feature + some basic recipes I created to get you started: https://github.com/liamcain/obsidian-calendar-plugin/wiki#custom-styling-based-on-tags

For open tasks, there should be a [hollow dot](https://github.com/liamcain/obsidian-calendar-plugin#what-do-the-dots-mean) already to indicate that the day has open tasks.

Let me know if that helps!

---

Also make sure you're running the latest version of the plugin (v1.4.11). I do frequent releases so it's easy to miss changes.

**Comment by adxsoft** [comment]
Hi Liam

Wow .. thats great feedback .. Thanks!.

I will make sure I keep up the updates for your excellent plugin and
checkout frontmatter which looks very interesting.

Its great how the whole ecosystem around Obsidian and plugins is so
flexible.

Cheers
Allan @ adxsoft


On Jan 1, 2021 at 02:54, Liam Cain <notifications@github.com> wrote:

Hi Allan,

This is actually currently possible if you're comfortable with frontmatter
<https://publish.obsidian.md/help/Advanced+topics/YAML+front+matter>. I'm
considering this a beta feature for now; in the future, I will likely add
support for tags anywhere in the file as well.

But here is the guide for how to use the feature + some basic recipes I
created to get you started:
https://github.com/liamcain/obsidian-calendar-plugin/wiki#custom-styling-based-on-tags

For open tasks, there should be a hollow dot
<https://github.com/liamcain/obsidian-calendar-plugin#what-do-the-dots-mean>
already to indicate that the day has open tasks.

Let me know if that helps!
------------------------------

Also make sure you're running the latest version of the plugin (v1.4.11). I
do frequent releases so it's easy to miss changes.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/liamcain/obsidian-calendar-plugin/issues/96#issuecomment-752993308>,
or unsubscribe

**Comment by adxsoft** [comment]
Hi Liam

I missed the implication of the hollow dot indicating open tasks, this is just what I needed for visually spotting open tasks.

I’ll fiddle with the frontmatter to get the day number coloring going.

Thanks Once again!

Cheers

Allan @ adxsoft
