### ISSUE TITLE
wrong week numbers

### ISSUE THREAD

**Issue by uxsdi** [liamcain/obsidian-calendar-plugin#97]
Please note that week number should correspond to a standardized value:
[What's the Current Week Number?](https://www.epochconverter.com/weeknumbers)

**Comment by liamcain** [comment]
Hi @uxsdi, Week numbers are configured based on your locale and follows this spec: https://en.wikipedia.org/wiki/Week#Week_numbering. If you're on the latest version of the plugin (v1.4.11) you should be able to check the locale that the plugin is using in `Settings > Calendar`. Scroll down to the bottom and there should be Advanced Settings with the configured locale. If you want to use ISO week numbering, you can set this to en-GB.

![image](https://user-images.githubusercontent.com/693981/103470456-81736080-4d40-11eb-9b9a-3746366e0e05.png)


If you don't see that setting, you might need to update the plugin.

![image](https://user-images.githubusercontent.com/693981/103470435-407b4c00-4d40-11eb-8ced-3daaa3283109.png)

**Comment by jlcala** [comment]
I had the same issue as uxsdi, but when I changed the calendar to **en-GB**, the week numbers are now all shifted compared to the file that is created when I click the week number. For example, when I click the week 1 link, I get a request to create a file for 2020-53. My week 1 file is showing a pip under week 2. 

![image](https://user-images.githubusercontent.com/69041809/103652557-44ba8b80-4f31-11eb-954d-66b2b240b1af.png)

**Comment by liamcain** [comment]
Hi @jlcala, can you check to see if this is fixed in the latest version (v1.4.12)? I released a patch last night that might help.

**Comment by jlcala** [comment]
I am on the latest version (updated this morning). I was messing around with the weekly filename format and sorted it out. When I changed the format of the file name from YYYY-WW to YYYY-ww, they registered correctly. Shouldn't WW be the ISO week number, though? 

I'll create a new issue for the formatting weirdness. Thanks!

**Comment by np-22** [comment]
I am using latest version v1.4.12 with setting en-gb and gggg-ww. But the week # is still one off.
<img width="316" alt="image" src="https://user-images.githubusercontent.com/10591164/104854574-4b93b780-58bc-11eb-898c-f5723816d54f.png">

**Comment by liamcain** [comment]
Hi @np-22, could you provide a little more context? What week number are you expecting to see? The current week number for `en-GB` should be Week 2 so that screenshot looks correct.

**Comment by np-22** [comment]
Sorry my mistake. I thought week of Dec 28 should be week 1 of 2021. How should I set it up correctly?

**Comment by liamcain** [comment]
Going to close this thread since it should be addressed by [this comment](https://github.com/liamcain/obsidian-calendar-plugin/issues/97#issuecomment-753557567). If that's not the case, feel free to reopen!
